.gitignore, .vscode/settings.json, README.md
[1]: https://github.com/spring-projects/spring-batch/blob/main/CONTRIBUTING.md
=> Fix errors and omissions in docs

spring-ai-docs/src/main/antora/modules/ROOT/pages/concepts.adoc
Fix typo in concepts.adoc
before:   List<Double   
after :     List\<Double\>
=> add "List<Double>" right bracket

document-readers/pdf-reader/pom.xml
that conflicts with spring-jcl.
without this exclusion
```
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
```
will be logged.
=> Exclude commons-logging

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/openai/OpenAiAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/openai/OpenAiProperties.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/openai/OpenAiPropertiesTests.java
This applies Spring Boot's style to the definition of `@ConfigurationProperties` classes (for [example](https://github.com/spring-projects/spring-boot/blob/v3.1.5/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/RedisProperties.java)) to `OpenAiProperties`.
I am somewhat undecided about defining a proper, additional property namespace for the AI client, such as:
`spring.ai.openai.client.*`
For example:
`spring.ai.openai.client.api-key`.
=> Refine delineation of Embedding properties from OpenAI (client) properties

README.md
I learned the hard way that GLFS must be installed to clone the repo and added a hint to the README.
=> Add hint about cloning the repo

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/aiclient.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/index.adoc
Fix links in the documentation on pages
- Overview
- AiClient
- Vector Databases
=> Fix documentation links

README.md
This PR fixes "FROM" group ID in the `README.md` by restoring "experimental" as it seems to have been dropped in 6d3c429e95a6906a1e674ac5bfb1bf5f9b8c37f2 accidentally.
=> Fix "FROM" group ID in README.md

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/aiclient.adoc
This PR fixes a broken Asciidoctor syntax in the `aiclient.adoc`.
=> Fix broken Asciidoctor syntax in aiclient.adoc

spring-ai-core/src/main/java/org/springframework/ai/embedding/Embedding.java
This pull request updates the toString() method in the Embedding class.
The change replaces the usage of size() with isEmpty() when checking the embedding collection, making the code more concise and semantically accurate.
=> Refactor toString() method in Embedding class

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/milvus/MilvusVectorStoreAutoConfiguration.java
=> fix: copy embedding dimension

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
Some OpenAI compatible servers have unknown properties in the error response, so it is better to use an existing ObjectMapper in the ErrorHandler.
=> Use `ObjectMapper` with `FAIL_ON_UNKNOWN_PROPERTIES` false during error handling

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/clients/openai.adoc
- `@RequestParam` annotation was incorrectly written as `P@RequestParam`
- fix generateStream example
- Improved API visibility
---
* Sign the [contributor license agreement](https://cla.pivotal.io/sign/spring) ✅
* Rebase your changes on the latest `main` branch and squash your commits ✅
* Add/Update unit tests as needed ✅
* Run a build and make sure all tests pass prior to submission ✅
=> Fix a typo in openai.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/clients/azure-openai.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/output-parser.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/prompt.adoc
I updated the usage of examples in the Spring AI API topic in the docs.
=> Update usage from aiClient to chatClient in docs

vector-stores/spring-ai-chroma/src/main/java/org/springframework/ai/chroma/ChromaApi.java
- According to `api.yaml`, `/api/v1/collections` path doesn't need slash so remove it
=> Remove slash according to api

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/neo4j.adoc, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/neo4j/Neo4jVectorStoreAutoConfigurationIT.java, vector-stores/spring-ai-neo4j-store/src/main/java/org/springframework/ai/vectorstore/Neo4jVectorStore.java, vector-stores/spring-ai-neo4j-store/src/test/java/org/springframework/ai/vectorstore/Neo4jVectorStoreIT.java
To make the Neo4j module more future-proof, this commit replaces the old vector index creation syntax with the new style. Also, the new pattern is in line with the standard Neo4j index creation and supports the _IF NOT EXISTS_ clause to run idempotent. This allows us to remove the preceding call to check if the index exists.
As a consequent, the module will require Neo4j to be at least on version 5.15.
=> Use the new vector index creation syntax for Neo4j

spring-ai-docs/src/main/antora/modules/ROOT/pages/concepts.adoc
Changing String package from `java.util.String` to `java.lang.String`
=> Changing String package from `java.util.String` to `java.lang.String`

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/clients/mistralai-chat.adoc
- Add Chat properties options
- Fix spring.ai.mistralai.chat.options.model descritption
- Add Mistral AI API Samples
=> Docs: Update Mistral AI Chat documentations

spring-ai-docs/src/main/antora/modules/ROOT/pages/upgrade-notes.adoc
There are some incorrect descriptions and 404 page-link in the `https://docs.spring.io/spring-ai/reference/upgrade-notes.html`, and I have made some modifications based on the code and the configuration page on the official website.
yes, done
yes,done
fix document, not nedd
fix document, not nedd
=> fix description of openapi-chat  in upgrade-notes

spring-ai-docs/src/main/antora/modules/ROOT/pages/getting-started.adoc
MistralAI Chat Completion API and  Embedding API is missing in getting started doc section.
This PR add MistralAI links to getting started doc section.
=> Add MistralAI links to getting started doc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/clients/openai-chat.adoc
Fixed #442 
```java
var openAiApi = new OpenAiApi(System.getenv("OPENAI_API_KEY"));
var chatClient = new OpenAiChatClient(openAiApi)
.withDefaultOptions(OpenAiChatOptions.builder()
.withModel("gpt-3.5-turbo")            // gpt-35-turbo => gpt-3.5-turbo
.withTemperature(0.4)
.withMaxTokens(200)
.build());
ChatResponse response = chatClient.call(
new Prompt("Generate the names of 5 famous pirates."));
```
=> Fix typo in model name, fixed #442

models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/titan/BedrockTitanChatOptions.java
Fixed typo in Bedrock Titan chat option for UnsupportedOperationException. 
I have changed the type from 'Titian' to 'Titan'
This fix is against issue - [link](https://github.com/spring-projects/spring-ai/issues/426)
=> #426 -Fixed typo in Bedrock Titan chat option exception

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/neo4j/Neo4jVectorStoreAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/neo4j/Neo4jVectorStoreProperties.java, vector-stores/spring-ai-neo4j-store/src/main/java/org/springframework/ai/vectorstore/Neo4jVectorStore.java, vector-stores/spring-ai-neo4j-store/src/test/java/org/springframework/ai/vectorstore/Neo4jVectorStoreIT.java
Some users' use-cases going not the complete SpringAI path from document creation to search (and chat) but are working with an already existing dataset (incl. embeddings).
To align with their needs, some more customization will allow them to work with those data instead of patching their dataset to match SpringAI's `Document` definition without any benefit for them.
Unrelated to this change, the Neo4j test version increased to be current.
=> Allow more customization for Neo4j store (id and constraint).

spring-ai-spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
It seems to have been missed in https://github.com/spring-projects/spring-ai/issues/242.
=> Add PostgresMlAutoConfiguration to AutoConfiguration.imports

vector-stores/spring-ai-mongodb-atlas-store/src/test/java/org/springframework/ai/vectorstore/MongoDBAtlasContainer.java
`Reuse Container` is a Testcontainers experimental feature. It requires `testcontainers.reuse.enable=true` in `~/.testcontainers.properties` in order to take effect but in order to avoid surprises, this commit remove it.
See https://java.testcontainers.org/features/reuse/
=> Remove withReuse in MongoDBAtlasContainer

README.md
While reading the README I have noticed an incomplete list of models and updated it based on what I see in the pom.xml modules section.
=> Update list of supported AI models in the main README.MD

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/speech.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/getting-started.adoc
- Adding Transcription Models and Text-To-Speech in 'Add dependencies for specific components' section
- Rename title Speech API to Text-To-Speech (TTS) API in speech.doc
=> Update getting-started documentation

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/openai-chat-functions.adoc
Fixing a small typo in the Function Calling doc page.
=> Fix typo in openai-chat-functions.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
I found the  `.withDefaultOptions()` is no longer found with `new OpenAiChatClient`  in the 0.8 SNAPSHOT while trying out the sample code, I have tried with my codebase and it responded with no errors, this is my first time contributing so please bear with me 😅 and thank you for the hard work!
=> Update openai-chat.adoc - replace withDefaultOptions()

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaOptions.java
=> Ollama: remove invalid embedding_only option

models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/AnthropicChatClientIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/mistralai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/mistralai-embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/openai-embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/image/openai-image.adoc, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/retry/SpringAiRetryAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/retry/SpringAiRetryProperties.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/retry/SpringAiRetryPropertiesTests.java
- Add a new autoconfig property spring.ai.retry.on-http-codes that list status codes (scuh as 429) for which the retry should be attemptd.
- Updated the docs.
=> Allow Retry on choosen status codes

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/watsonx-ai-chat.adoc, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/watsonxai/WatsonxAiChatProperties.java
This will fix the issue #510 
- Fix typo in watsonx.ai chat client documentation
- Add default model to watsonx.ai chat client documentation
- Add default model to WatsonxAiChatProperties
=> FIX: Add watosnx.ai default model

vector-stores/spring-ai-azure/src/main/java/org/springframework/ai/vectorstore/azure/AzureVectorStore.java
For a scenario when you are adding documents to the Azure AI Search Vector store (using the AzureVectorStore java implementation), I noticed when the document content is not loaded successfully a message of this nature could be thrown  
"Document with key 1 upload is not successfully".
This sounds grammatically incorrect. So I have updated the message to "Document with key 1 did not upload successfully".
Exact change as follows -
```
for (IndexingResult indexingResult : result.getResults()) {
Assert.isTrue(indexingResult.isSucceeded(),
String.format("Document with key %s did not upload successfully", indexingResult.getKey()));
}
```
@pivotal-cla This is an Obvious Fix.
=> AzureVectorStore - Correct message grammar in the add method for a scenario when the document was not uploaded successfully

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaChatClient.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/metadata/OllamaChatResponseMetadata.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/metadata/OllamaUsage.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaChatClientIT.java
The `Usage` of Ollama `ChatResponse` was put into `ChatGenerationMetadata` as content filter metadata. The correct place should be in the `Usage` of `ChatResponseMetadata`. New implementations of `ChatResponseMetadata` and `Usage` are created for Ollama.
Fix #397
=> Fix Usage in Ollama ChatResponse

spring-ai-core/src/main/java/org/springframework/ai/transformer/splitter/TextSplitter.java
A correction has been made to the "page_number" value, which corresponded to the last page number.
Each chunk of text on a page will now have the page number as the 'page_number' metadata, instead of the last page number for the entire block.
=> Fixing metadata for text splitting

models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiChatOptions.java, models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureChatCompletionsOptionsTests.java
* Sign the [contributor license agreement](https://cla.pivotal.io/sign/spring) ✅
* Rebase your changes on the latest `main` branch and squash your commits ✅
* Add/Update unit tests as needed ✅
* Run a build and make sure all tests pass prior to submission ✅
---
I discovered a null safety issue while working with spring-ai in Kotlin. 
The `AzureOpenAiChatOptions` builder does not handle null values properly. 
Specifically, the `withFrequencyPenalty` and `withPresencePenalty` methods call `doubleValue()` without checking if the parameter is null.
Here is the problematic code:
```java
public Builder withFrequencyPenalty(Float …
```
=> fix: AzureOpenAiChatOptions to handle null values for presencePenalty and frequencyPenalty

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vertexai/gemini/VertexAiGeminiChatProperties.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vertexai/gemini/VertexAiGeminiAutoConfigurationIT.java
I'm not sure if there is a reason for it, but Vertex AI Gemini basic autoconfiguration didn't carry a default model, unlike some other implementations (like OpenAI's). 
Setting the default model makes it a little bit more _plugandplay'able_.
=> Add the default model to the initial Vertex AI Gemini autoconfiguration chat properties

document-readers/pdf-reader/pom.xml, models/spring-ai-ollama/pom.xml, models/spring-ai-postgresml/pom.xml, models/spring-ai-transformers/pom.xml, pom.xml, spring-ai-spring-boot-autoconfigure/pom.xml, spring-ai-spring-boot-testcontainers/pom.xml, vector-stores/spring-ai-chroma/pom.xml, vector-stores/spring-ai-elasticsearch-store/pom.xml, vector-stores/spring-ai-milvus-store/pom.xml, vector-stores/spring-ai-mongodb-atlas-store/pom.xml, vector-stores/spring-ai-neo4j-store/pom.xml, vector-stores/spring-ai-pgvector-store/pom.xml, vector-stores/spring-ai-qdrant/pom.xml, vector-stores/spring-ai-redis/pom.xml, vector-stores/spring-ai-weaviate/pom.xml
Spring Boot 3.2.4 offers Testcontainers 1.19.7, which provides all the modules needed by Spring AI. So, fixed testcontainers version has been removed.
Also, testcontainers-redis has been updated to 2.2.0.
=> Update spring-boot version to 3.2.4

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaEmbeddingClient.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaApi.java
=> Ollama: Added missing fields in API

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaChatClient.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaApi.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaOptions.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc
The Ollama documentation used to include a `template` parameter for the `chat completion` endpoint. However, that parameter only exists for the `generation` endpoint. It was probably a copy/paste mistake in the documentation. I have submitted a fix to the Ollama project which has now been merged (https://github.com/ollama/ollama/pull/3515).
This pull request is for removing the `template` parameter from the `ChatRequest` class and from the `OllamaOptions` class since it's not part of the Ollama API for Chat Completion. I have also updated the related documentation. The Ollama Server will not fail if the parameter is included, but it won't have any effect.
=> Ollama: Remove unused option in chat completion

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/pgvector.adoc
The filter expression within the document handling logic has been updated to enhance clarity and ensure accurate author filtering. Previously, the `in` function mistakenly included names as direct arguments, potentially leading to ambiguity in filter application. This has been corrected by explicitly specifying the `author` field, ensuring the filter accurately applies to author names only. This change improves the maintainability and readability of the code, particularly in sections dealing with article filtering based on authorship and type.
- Correct the filter expression by explicitly specifying the `author` field.
- Ensure accurate and unambiguous author filtering in article management.
=> Refactor filter expression for clarity and accuracy

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc
I tried to run the example for Azure OpenAi in the [documentation](https://docs.spring.io/spring-ai/reference/api/clients/azure-openai-chat.html), however it seems that the API changed. 
I used the version 0.8.1.
After I got it to work, I adapted the code from the documentation accordingly.
I hope the changes fit. Let me know if you want me to adjust anything.
=> Update documentation for azure open ai chat

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/anthropic3/BedrockAnthropic3ChatAutoConfiguration.java
When enabling bedrock anthropic and anthropic3 at the same time, it will throw the bean name conflict exception.
```
spring:
ai:
bedrock:
anthropic:
chat:
enabled: true
anthropic3:
chat:
enabled: true
```
>
>The bean 'anthropicApi', defined in class path resource [org/springframework/ai/autoconfigure/bedrock/anthropic3/BedrockAnthropic3ChatAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/ai/autoconfigure/bedrock/anthropic/BedrockAnthropicChatAutoConfiguration.class] and overriding is disabled.
>
So change the anthropic3 to a proper bean name to avoid this issue.
=> Fix bean name conflicts when using BedrockAnthropic and BedrockAnthropic3 at the same time.

models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/anthropic/api/AnthropicChatBedrockApi.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/anthropic3/api/Anthropic3ChatBedrockApi.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/api/AbstractBedrockApi.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/cohere/api/CohereChatBedrockApi.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/cohere/api/CohereEmbeddingBedrockApi.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/jurassic2/api/Ai21Jurassic2ChatBedrockApi.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/llama2/api/Llama2ChatBedrockApi.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/titan/api/TitanChatBedrockApi.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/titan/api/TitanEmbeddingBedrockApi.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/bedrock.adoc, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/BedrockAwsConnectionConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/anthropic/BedrockAnthropicChatAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/anthropic3/BedrockAnthropic3ChatAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/cohere/BedrockCohereChatAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/cohere/BedrockCohereEmbeddingAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/jurrasic2/BedrockAi21Jurassic2ChatAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/llama2/BedrockLlama2ChatAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/titan/BedrockTitanChatAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/titan/BedrockTitanEmbeddingAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/bedrock/BedrockAwsConnectionConfigurationIT.java
Re-write Bedrock `BedrockAwsConnectionConfiguration` to use `AwsCredentialsProvider` and `AwsRegionProvider` to manage Amazon Bedrock AI model connections.
With this change, `Spring-AI` will provide the capability to customize the `AwsCredentialsProvider` and `AwsRegionProvider` configurations. Also with this feature, `Spring-AI` has capabilities compatible with `Spring Cloud AWS` credential management.
=> Bedrock client auto-configuration support external AwsCredentialsProvider and AwsRegionProvider

models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/aot/BedrockRuntimeHints.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/titan/BedrockTitanEmbeddingClient.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/titan/BedrockTitanEmbeddingOptions.java, models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/titan/BedrockTitanEmbeddingClientIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/bedrock-titan-embedding.adoc
`BedrockTitanEmbeddingClient` only support configuration embedding type when startup in `BedrockTitanEmbeddingProperties.inputType` property. 
Add new `BedrockTitanEmbeddingOptions` to support dynamic embedding request types while runtime.
For example:
```
bedrockTitanEmbeddingClient.call(new EmbeddingRequest(List.of("hello world"),
BedrockTitanEmbeddingOptions.builder().withInputType(InputType.TEXT).build()));
```
=> Bedrock Titan embedding client support dynamic embedding request types.

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/anthropic-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/azure-open-ai-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/mistralai-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/openai-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/vertexai-gemini-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/mistralai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/mistralai-embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/onnx.adoc
Fix typos in the function calling and embedding model documentation for specific models.
There are many duplicated sections across the different model docs. It might be worth looking into extracting those sections into AsciiDoc fragments to re-use them (and simplify the maintenance).
=> Docs: Fix typos in embedding and function calling documentation

vector-stores/spring-ai-cassandra/src/main/java/org/springframework/ai/vectorstore/CassandraVectorStoreConfig.java
This also is a fix for AstraDB, which throws an exception if you try to `CREATE KEYSPACE IF NOT EXISTS …`
This PR looks like more change than it really is.
It is actually only two lines, the body of both the `ensureKeyspaceExists()` and `ensureTableExists(..)` methods are wrapped in an `if` statement.
-  https://github.com/spring-projects/spring-ai/blob/c07663a3effb2e7cfee24943777b33b3f7d09f42/vector-stores/spring-ai-cassandra/src/main/java/org/springframework/ai/vectorstore/CassandraVectorStoreConfig.java#L471
- https://github.com/spring-projects/spring-ai/blob/c07663a3effb2e7cfee24943777b33b3f7d09f42/vector-stores/spring-ai-cassandra/src/main/java/org/springframework/ai/vectorstore/CassandraVectorStoreConfig.java#L568
=> Avoid calling `CREATE KEYSPACE|TABLE IF NOT EXISTS …` unnecessarily

vector-stores/spring-ai-cassandra/src/main/java/org/springframework/ai/vectorstore/CassandraVectorStore.java, vector-stores/spring-ai-cassandra/src/main/java/org/springframework/ai/vectorstore/CassandraVectorStoreConfig.java, vector-stores/spring-ai-cassandra/src/test/java/org/springframework/ai/vectorstore/CassandraVectorStoreIT.java
Also ensures embeddings are in documents when storing them, so the caller can access them if so required.
=> CassandraVectorStore option to return embeddings in documents from similarity searches

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/elasticsearch.adoc
I fixed a mistake in our documentation that incorrectly mentioned SQL's WHERE. We actually use Elasticsearch's Query string query. This update makes sure our guide is right.
=> Docs: Fix filter expression reference to Elasticsearch Query string query

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/pgvector.adoc
During my use of the PgVectorStore, I noticed the documentation mistakenly referenced `dimension` instead of `dimensions`. I corrected this to align with the correct configuration properties and to assist others in setting up their environments correctly. Here’s an update on the pull request.
Please let me know if there’s anything else needed on my end. Thank you for the opportunity to contribute!
=> docs: Fix typo in PgVectorStore dimensions property

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/cassandra/CassandraVectorStoreAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/cassandra/CassandraVectorStoreProperties.java
ref: https://github.com/spring-projects/spring-ai/pull/673
=> Add the autoconfigure property for the CassandraVectorStore option to return embeddings in documents from similarity searches

models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/titan/api/TitanEmbeddingBedrockApi.java, models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/titan/api/TitanEmbeddingBedrockApiIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/bedrock-titan-embedding.adoc
Amazon Titan Text Embeddings V2 now available in Amazon Bedrock: https://aws.amazon.com/about-aws/whats-new/2024/04/amazon-titan-text-embeddings-v2-amazon-bedrock/
=> AWS Bedrock Titan embedding model add Text Embeddings V2 support.

vector-stores/spring-ai-chroma/src/main/java/org/springframework/ai/chroma/ChromaApi.java, vector-stores/spring-ai-chroma/src/test/java/org/springframework/ai/vectorstore/BasicAuthChromaWhereIT.java, vector-stores/spring-ai-chroma/src/test/java/org/springframework/ai/vectorstore/TokenSecuredChromaWhereIT.java, vector-stores/spring-ai-chroma/src/test/resources/server.htpasswd
Currently, `username` is added as a password in `BasicAuthenticationInterceptor`. This commit fixes the issue and also make sure the integration test setup is correct.
=> Fix ChromaDB basic authentication

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
Add gpt-4o to OpenAI chat models enum and update JavaDoc
=> OpenAI: Add gpt-4o to chat model enum

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/qdrant/QdrantVectorStoreProperties.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/qdrant/QdrantVectorStoreAutoConfigurationIT.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/qdrant/QdrantVectorStorePropertiesTests.java, vector-stores/spring-ai-qdrant/src/main/java/org/springframework/ai/vectorstore/qdrant/QdrantVectorStore.java
Add a default collection name similar to other vector store implementations. Currently, when using starters, qdrant requires a collection name. Otherwise, it fails.
=> Add default collection name to Qdrant

models/spring-ai-ollama/pom.xml
Fixes #546 
In short: I'm getting a `ClassNotFoundException` for `NonTransientAiException` when trying to use the Ollama model dependency. It works if I explicitly add it to my build. Meanwhile I don't need to do that for OpenAI because it's already in that module's build.
=> Add spring-ai-retry dependency to Ollama model pom.xml

spring-ai-core/src/main/java/org/springframework/ai/converter/MapOutputConverter.java
- Add an additional instruction to the format for the model not to include markdown syntax for JSON quotes.
- Extend the conversion to strip markdown quotes in case the model included them in the response
=> Extend format to improve generate JSON

spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/QuestionAnswerAdvisor.java
Although it's helpful to be able to customize the `SearchRequest` given to `QuestionAnswerAdvisor`, it's not uncommon to just rely on `SearchRequest.defaults()`. Therefore, this PR overloads the constructor with a version that only requires a `VectorStore` and uses `SearchRequest.defaults()`...in the interest of simplifying the application code a little.
=> Overload QuestionAnswerAdvisor to use SearchRequest.defaults()

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
Small change to replace the plain text web link to HTML link and correct usage of an indefinite article
=> Minor javadoc improvements

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/anthropic-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/minimax-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/mistralai-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/openai-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/zhipuai-chat-functions.adoc
I updated the documents for Anthropic, Mistral, ZhuPu, MiniMax, and OpenAI to match up with what is in the docs for Azure OpenAI to use the FunctionCallbackWrapper builder. In doing so the call to set to response converter was lost, although it could have been specified...it just wasn't in the Azure example.
I also noticed that the Gemini document also sets the schema type, as it's required for Gemini. I confirmed that it's not required for OpenAI, Anthropic, or Mistral. But while confirming, I discovered that the documentation for Mistral functions refers to "mistral_large_latest", but it should be "mistral-large-latest". The same fix was also needed for "mistral_small_latest" -> "mistral-small-latest".
=> Update FunctionCallbackWrapper docs for Anthropic, Mistral, ZhiPu, MiniMax, and OpenAI

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/pgvector.adoc
* Added tips for running PGvector as a Spring Boot dev service
* Fixed typos in code snippets
* Updated the PGvector image name
* Improved syntax
=> [PGvector] Improve documentation

models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/MistralAiChatModel.java, models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/api/MistralAiApi.java, models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiRetryTests.java, models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiTestConfiguration.java, models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/api/MistralAiApiIT.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/mistralai/MistralAiChatProperties.java
* Align model naming with Mistral AI documentation
* Add missing model for mixtral 22B
* Deprecate mistral-medium-latest because Mistral will remove it soon
=> [Mistral] Update models

models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiChatModel.java
Fix #827 
Wrap `chatCompletions.getChoices()` using `nullSafeList` to avoid potential NPE
=> Fix potential NPE in AzureOpenAiChatModel

document-readers/tika-reader/pom.xml
this PR upgrades Apache Tika from version 2.9.0 to 2.9.2 to address the following security vulnerabilities:  
- CVE-2024-26308  
- CVE-2024-25710  
- CVE-2023-42503  
- CVE-2024-21742  
The current version of Apache Tika (2.9.0) includes dependencies on Apache Commons Compress 1.23.0 and apache-mime4j 0.8.9, which are affected by the aforementioned vulnerabilities.   
Upgrading to Apache Tika 2.9.2 will automatically resolve these issues as the newer version includes updated dependencies that address the vulnerabilities.  
- [Apache Commons Compress CVEs](https://commons.apache.org/proper/commons-compress/security.html)  
- [Apache MIME4J CVEs](https://james.apache.org/james/update/2024/01/08/mime4j-0.8.10.html)
=> Upgrade Apache Tika to version 2.9.2 to address security vulnerabilities

.editorconfig
To help the rest of us who are not using tabs for indentation.
Taken from https://github.com/spring-projects/spring-framework/blob/main/.editorconfig
=> Introduce .editorconfig

pom.xml, spring-ai-spring-boot-autoconfigure/pom.xml
Spring AI relies on spring boot 3.3.0 (providing Testcontainers 1.19.8).
The property is downgrading the version.
=> Remove `testcontainers.version` property

vector-stores/spring-ai-milvus-store/src/main/java/org/springframework/ai/vectorstore/MilvusVectorStore.java
Use List.of instead of Arrays.asList In the SEARCH_OUTPUT_FIELDS field.
The Arrays.asList method can change elements. SEARCH_OUTPUT_FIELDS is an immutable field, so it has been improved to util List.of.
=> Use List.of instead of Arrays.asList In the SEARCH_OUTPUT_FIELDS field.

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/docker-compose.adoc, spring-ai-spring-boot-docker-compose/src/main/java/org/springframework/ai/docker/compose/service/connection/redis/RedisDockerComposeConnectionDetailsFactory.java, spring-ai-spring-boot-docker-compose/src/test/java/org/springframework/ai/docker/compose/service/connection/redis/RedisStackDockerComposeConnectionDetailsFactoryTests.java, spring-ai-spring-boot-docker-compose/src/test/java/org/springframework/ai/docker/compose/service/connection/redis/RedisStackServerDockerComposeConnectionDetailsFactoryTests.java
Currently, `redis/redis-stack-server` image is supported. This commit introduces support for `redis/redis-stack`, which also contains Redis Insight.
=> Add support for redis/redis-stack image in Docker Compose

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/qdrant/QdrantConnectionDetails.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/qdrant/QdrantVectorStoreAutoConfiguration.java, spring-ai-spring-boot-docker-compose/src/main/java/org/springframework/ai/docker/compose/service/connection/qdrant/QdrantDockerComposeConnectionDetailsFactory.java, spring-ai-spring-boot-docker-compose/src/main/java/org/springframework/ai/docker/compose/service/connection/qdrant/QdrantEnvironment.java, spring-ai-spring-boot-docker-compose/src/test/java/org/springframework/ai/docker/compose/service/connection/qdrant/QdrantDockerComposeConnectionDetailsFactoryTests.java, spring-ai-spring-boot-docker-compose/src/test/resources/org/springframework/ai/docker/compose/service/connection/qdrant/qdrant-compose.yaml, spring-ai-spring-boot-testcontainers/src/main/java/org/springframework/ai/testcontainers/service/connection/qdrant/QdrantContainerConnectionDetailsFactory.java, spring-ai-spring-boot-testcontainers/src/test/java/org/springframework/ai/testcontainers/service/connection/qdrant/QdrantContainerWithApiKeyConnectionDetailsFactoryTest.java
Read `QDRANT__SERVICE__API_KEY` env var from compose file and Testcontainers definition to configure the connection details for Qdrant.
=> Support Qdrant's Api Key in Docker Compose and Testcontainers

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/openai-embeddings.adoc
- fix base-url error in openai-embeddings.adoc
- When I set `spring.ai.openai.base-url=api.openai.com` as the document, I meet the Error `URI is not absolute`
- It is necessary to set the base-url with `https`(`spring.ai.openai.base-url=https://api.openai.com` )
=> Fix:base-url Error in openai-embeddings.adoc

spring-ai-spring-boot-docker-compose/src/main/java/org/springframework/ai/docker/compose/service/connection/chroma/ChromaEnvironment.java, spring-ai-spring-boot-docker-compose/src/test/java/org/springframework/ai/docker/compose/service/connection/chroma/ChromaEnvironmentTests.java, spring-ai-spring-boot-testcontainers/src/main/java/org/springframework/ai/testcontainers/service/connection/chroma/ChromaContainerConnectionDetailsFactory.java, spring-ai-spring-boot-testcontainers/src/test/java/org/springframework/ai/testcontainers/service/connection/chroma/ChromaWithToken2ContainerConnectionDetailsFactoryTest.java
Currently, Docker Compose and Testcontainers support `CHROMA_SERVER_AUTHN_CREDENTIALS`, which is provided by Chroma 0.5.x. Previous versions use `CHROMA_SERVER_AUTH_CREDENTIALS` instead.
=> Support Chroma's CHROMA_SERVER_AUTH_CREDENTIALS env var from version 0.4.x

spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/weaviate/WeaviateVectorStoreAutoConfigurationTests.java, spring-ai-spring-boot-testcontainers/src/test/java/org/springframework/ai/testcontainers/service/connection/weaviate/WeaviateContainerConnectionDetailsFactoryTest.java, vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/WeaviateVectorStoreIT.java
Currently, Testcontainers Weaviate implementation relies on port availability.
This commit switch to Weaviate's readiness endpoint.
=> Use Weaviate's readiness endpoint

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/ollama-embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/pinecone.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/typesense.adoc
Corrected typographical errors in key documents:
- `pinecone.adoc` (origina -> original)
- `typesense.adoc` (retrieveing -> retrieving)
- `ollama-chat.adoc` (revise capital case)
- `ollama-embeddings.adoc` (Mpdel -> Model)
revised #961.
Thanks for reviewing.
=> Update selective typo corrections in documentation

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/redis.adoc
The dependency should be spring-ai-redis-store-spring-boot-starter instead of spring-ai-transformers-spring-boot-starter for Redis vector store
=> Update redis.adoc to correct the dependency for Redis vector store

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatModel.java
* Fix OpenAiChatModel NPE using getOrDefault
closed #970 
I fixed this issue using `Map.getOrDefault`
=> Fix OpenAiChatModel NPE

document-readers/tika-reader/pom.xml
Apache tika 2.x.x wants old version of PDFBox 2.x, bump to tika 3.0.0-BETA that want PDFBox 3.x. With this we can use Tika as PDF reader.
=> Bump Tika to avoid PDFBox conflicts

spring-ai-spring-boot-autoconfigure/pom.xml
The `spring-ai-spring-boot-autoconfigure` module had a few dependencies that were included in the final JAR instead of being marked as optional (it's the starter dependency that is supposed to include compile-scope dependencies when needed).
Also, the PostgreSQL dependency was duplicated.
=> Fix leaked dependencies in autoconfigure module

spring-ai-core/src/main/java/org/springframework/ai/converter/BeanOutputConverter.java
Small fix to register the JavaTimeModule to ObjectMapper in BeanOutputConverter.
=> Registering JavaTimeModule to ObjectMapper

spring-ai-docs/src/main/antora/modules/ROOT/pages/concepts.adoc
Corrects grammar in "`AI Concepts`" document, "Retrieval Augmented Generation" and "Function Calling" sections.
=> Correct grammar in RAG and Function Calling sections

document-readers/pdf-reader/src/main/java/org/springframework/ai/reader/pdf/config/PdfDocumentReaderConfig.java
This appears to be a copy-and-paste issue.
=> Fix not-null assertion in PdfDocumentReaderConfig

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
Hello 
Currently, GPT_4_VISION_PREVIEW will continue to be available only to existing users of this model starting June 17, 2024. So, when a request is made, the following response code is returned.
```kotlin
val path = Paths.get("/Users/yeseong0412/Desktop/alpha-map-server/multimodal.test.png");
val imageData = Files.readAllBytes(path);
val userMessage = UserMessage("Explain what do you see on this picture?",
listOf(Media(MimeTypeUtils.IMAGE_PNG, imageData)))
val response = openAiChatModel.call(
Prompt(listOf(userMessage),
OpenAiChatOptions.Builder()
.withModel(OpenAiApi.ChatModel.GPT_4_VISION_PREVIEW.value)
.build())
)
```
```json
{
"error": {
"message": "The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations",
"type": …
```
=> Added information about models that are no longer supported

pom.xml
Adds o200k_base encoding used by gpt4o and gpt4o-mini
=> Update jtokkit from 1.0.0 to 1.1.0

spring-ai-bom/pom.xml
Fix missing "spring-ai-spring-cloud-bindings" in Spring AI BOM
=> Add Cloud Bindings module to Spring AI BOM

vector-stores/spring-ai-milvus-store/src/main/java/org/springframework/ai/vectorstore/MilvusVectorStore.java
[Typically, this method is called once all the data is ingested. You are advised not to call this method frequently since it could generate a lot of tiny segments and lead to unstable problems.
](https://milvus.io/api-reference/java/v2.4.x/v1/Collection/flush.md)
I found that the flush operation is time-consuming, and frequent flush operations result in the creation of many segments, which can impact performance. This also increases the pressure during the compaction process.
=> Remove flush operations to prevent excessive segment creation in Milvus

vector-stores/spring-ai-mongodb-atlas-store/src/main/java/org/springframework/ai/vectorstore/MongoDBAtlasVectorStore.java
`org.bson.Document`s have been the preferred document structure since the 3.0 release of the mongo-java-driver. This PR replaces the `BasicDBObject` for `org.bson.Document` also removes the need for `@SuppressWarnings("unchecked")` from within the code.
=> Updated MongoDBAtlasVectorStore to use `org.bson.Document`

models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/AnthropicChatModel.java, models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiChatModel.java, models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/MistralAiChatModel.java, models/spring-ai-vertex-ai-gemini/src/main/java/org/springframework/ai/vertexai/gemini/VertexAiGeminiChatModel.java, spring-ai-core/src/main/java/org/springframework/ai/chat/model/AbstractToolCallSupport.java
fix `AbstractToolCallSupport` wrong method name `executeFuncitons` -> `executeFunctions`
=> fix: AbstractToolCallSupport wrong method name

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatOptions.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
=> Add OpenAI paralel funciton call option

models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelIT.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/chat/observation/ChatObservationAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/embedding/observation/EmbeddingObservationAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/chat/observation/ChatObservationAutoConfigurationTests.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/embedding/observation/EmbeddingObservationAutoConfigurationTests.java
Right now, it's conditional on the class. It must be conditional on the presence of a `MeterRegistry` bean instead.
=> Make MeterObservationHandler conditional on MeterRegistry bean

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaEmbeddingModel.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaApi.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaOptions.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaEmbeddingModelIT.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaEmbeddingModelTests.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaEmbeddingRequestTests.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/api/OllamaApiIT.java, spring-ai-core/src/main/java/org/springframework/ai/embedding/Embedding.java, spring-ai-core/src/main/java/org/springframework/ai/transformer/splitter/TextSplitter.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/ollama-embeddings.adoc
- Update OllamaEmbeddingModel to support batch embedding requests
- Rename EmbeddingRequest/Response to EmbeddingsRequest/Response
- Add truncate option to control input truncation
- Update documentation and tests for new embedding API
- Remove deprecated withModel and withDefaultOptions methods
- Adjust default values for various Ollama model options
Resolves #1158
=> Refactor Ollama embedding model implementation

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/pinecone.adoc
```
List <Document> documents = List.of(
new Document("Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!!", Map.of("meta1", "meta1")),
new Document("The World is Big and Salvation Lurks Around the Corner"),
new Document("You walk forward facing the past and you turn back toward the future.", Map.of("meta2", "meta2")));
// Add the documents
vectorStore.add(List.of(document));
```
To
```
List <Document> documents = List.of(
new Document("Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!!", Map.of("meta1", "meta1")),
new Document("The World is Big and Salvation Lurks Around the Corner"),
new Document("You walk forward facing the past and you turn back toward the future.", Map.of("meta2", "meta2")));
// Add the …
```
=> Docs: Edit pinecone example

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/onnx.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/structured-output-converter.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/concepts.adoc
Easy for native speakers, I know.
=> Correct some grammar typos with 'latter'

spring-ai-core/src/main/java/org/springframework/ai/chat/client/ChatClient.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/DefaultChatClient.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/DefaultChatClientBuilder.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/RequestResponseAdvisor.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientInputContentObservationFilter.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientObservationContext.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientObservationConvention.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientObservationDocumentation.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/DefaultChatClientObservationConvention.java, spring-ai-core/src/main/java/org/springframework/ai/observation/conventions/AiOperationType.java, spring-ai-core/src/main/java/org/springframework/ai/observation/conventions/AiProvider.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/ChatClientInputContentObservationFilterTests.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/ChatClientObservationContextTests.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/DefaultChatClientObservationConventionTests.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/chat/client/ChatClientAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/chat/client/ChatClientBuilderProperties.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/chat/client/ChatClientObservationAutoConfigurationTests.java
- Introduce ObservationRegistry to ChatClient creation and builder methods
- Implement observable chat responses in DefaultChatClient
- Add ChatClientObservationContext and related classes for metrics
- Update ChatClientAutoConfiguration to support ObservationRegistry
- Enhance RequestResponseAdvisor with getName() method
=> Add observability support for ChatClient

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/azure.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/oracle.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/redis.adoc
Corrected the variable passed to vectorStore.add() from List.of(document) to documents.
```java
List <Document> documents = List.of(
new Document("Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!!", Map.of("meta1", "meta1")),
new Document("The World is Big and Salvation Lurks Around the Corner"),
new Document("You walk forward facing the past and you turn back toward the future.", Map.of("meta2", "meta2")));
// Add the documents to Redis
vectorStore.add(List.of(document));
```
Corrected Code:
```java
List <Document> documents = List.of(
new Document("Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!! Spring AI rocks!!", Map.of("meta1", "meta1")),
new Document("The World is Big and Salvation Lurks Around the Corner"),
new …
```
=> docs: Edit Auto-configuration Example

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/chroma.adoc
Since `documents` is the list containing  `Document`objects 
`document` variable should be `documents` 
`vectorStore.add(List.of(document));`  -> `vectorStore.add(documents);`
=> docs : fix chroma.adoc example

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/audio/transcriptions/openai-transcriptions.adoc
The documentation of OpenAI Transcription API was likely copied from the Image API documentation, with several incorrect mentions of the OpenAI image model. This PR fixes the issue.
=> Fix typos in openai-transcriptions.adoc

models/spring-ai-openai/src/test/java/org/springframework/ai/openai/api/tool/OpenAiApiToolFunctionCallIT.java
To improve the readability of the test, I removed the unnecessary `if (responseMessage.toolCalls() != null)` check
The if statement is redundant and will always evaluate to true, since `assertThat(responseMessage.toolCalls()).isNotNull()` ensures that `toolCalls()` is not null.
=> Remove unnecessary if statement in 'toolFunctionCall' test code from OpenAiApiToolFunctionCallIT

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/mongo/MongoDBAtlasVectorStoreAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/mongo/MongoDBAtlasVectorStoreAutoConfigurationIT.java, vector-stores/spring-ai-mongodb-atlas-store/src/test/java/org/springframework/ai/vectorstore/MongoDBAtlasVectorStoreIT.java, vector-stores/spring-ai-mongodb-atlas-store/src/test/java/org/springframework/ai/vectorstore/MongoDbVectorStoreObservationIT.java
Remove the requirement of MongoDB vector store auto-configuration only after `MongoDataAutoConfiguration`. This enables the `MongoDBAtlasVectorStoreAutoConfiguration` to properly provide custom Mongo conversions.
In `MongoDBAtlasVectorStoreIT` and `MongoDbVectorStoreObservationIT` tests, properly provision the `MongoTemplate` with custom conversions as these tests are not relying on auto-configuration.
=> Fixing MongoDB vector store support test failures

spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/VectorStoreChatMemoryAdvisor.java, vector-stores/spring-ai-pgvector-store/src/test/java/org/springframework/ai/vectorstore/PgVectorStoreWithChatMemoryAdvisorIT.java
When `VectorStoreChatMemoryAdvisor`  is used the `SELECT` from the pgvector store failed with a SQL error.
This PR fixes the SQL by removing the `'` as reported.
I tried to provide a useful test that verifies the correct behaviour when `VectorStoreChatMemoryAdvisor` is used.
It verifies that chat messages are enriched with similar messages from the vector store. This query was failing.
=> Fix problem with VectorStoreChatMemoryAdvisor using pgvector

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/elasticsearch.adoc, vector-stores/spring-ai-elasticsearch-store/src/main/java/org/springframework/ai/vectorstore/ElasticsearchVectorStore.java
Fixes https://github.com/spring-projects/spring-ai/issues/1316 as discussed in the issue, also updates the documentation to better explain the various index initialization possibilities. 
Added `user-agent` header to the elasticsearch client configuration. This is what we at Elastic will use to keep track of the usage of Spring AI, so that we can see statistics in the [Elastic Cloud](https://cloud.elastic.co/) metrics, better understand the needs of Spring users and contribute more to the project.
=> Elasticsearch vector store - Wrong error reported fix

models/spring-ai-vertex-ai-gemini/src/main/java/org/springframework/ai/vertexai/gemini/VertexAiGeminiChatModel.java
The Google Gemini Vertex Chat Model was not adding previous Assistant Messages to the parts list - this results in a failure when submitting a call:
`Results in: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unable to submit request because it must include at least one parts field, which describes the prompt input. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini`
=> Fix where previous Assistant Messages were not being added to the parts list

vector-stores/spring-ai-chroma-store/src/main/java/org/springframework/ai/chroma/ChromaApi.java
I'm using chroma as a vector database for a demo with spring AI, and I've found that retrieving the collection name not only throws an **HttpServerErrorException**, but also an **HttpClientErrorException**.
I've pushed a fix to additionally capture HttpClientErrorException and added a Pattern to retrieve the error message.
Tests are green
=> Handle HttpClientErrorException on getCollection method

models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/AnthropicChatModelObservationIT.java, models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureOpenAiChatModelObservationIT.java, models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiChatModelObservationIT.java, models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiEmbeddingModelObservationIT.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaChatModelObservationIT.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaEmbeddingModelObservationIT.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaImage.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelObservationIT.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/proxy/OllamaWithOpenAiChatModelIT.java, spring-ai-core/src/main/java/org/springframework/ai/chat/observation/DefaultChatModelObservationConvention.java, spring-ai-core/src/main/java/org/springframework/ai/embedding/observation/DefaultEmbeddingModelObservationConvention.java, spring-ai-core/src/main/java/org/springframework/ai/image/observation/DefaultImageModelObservationConvention.java, spring-ai-core/src/main/java/org/springframework/ai/observation/conventions/AiOperationType.java, spring-ai-core/src/main/java/org/springframework/ai/observation/conventions/AiProvider.java, spring-ai-core/src/test/java/org/springframework/ai/chat/observation/DefaultChatModelObservationConventionTests.java, spring-ai-core/src/test/java/org/springframework/ai/embedding/observation/DefaultEmbeddingModelObservationConventionTests.java, spring-ai-core/src/test/java/org/springframework/ai/image/observation/DefaultImageModelObservationConventionTests.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/ollama/OllamaImage.java, spring-ai-spring-boot-testcontainers/src/test/java/org/springframework/ai/testcontainers/service/connection/ollama/OllamaContainerConnectionDetailsFactoryTest.java
Chat model observations support several key-value pairs, coming from the Spring AI abstractions. Currently, whenever a value is not available (either because not configured by the user or not supported by the model provider), span/metrics attributes are generated anyway with value "none". 
That causes several issues, including an unneeded increase in time series, challenges in alerting/monitoring (especially for integer/double attributes that suddenly are populated with a string), and non-compliance with the OpenTelemetry Semantic Conventions (according to which, attributes should be excluded altogether if there's no value). 
This pull request changes the conventions for chat model observation to exclude the generation of span/metrics attributes for optional values which don't have any …
=> Improve optional values handling in chat model observations

models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiChatModelObservationIT.java, spring-ai-core/src/main/java/org/springframework/ai/chat/observation/DefaultChatModelObservationConvention.java, spring-ai-core/src/main/java/org/springframework/ai/embedding/observation/DefaultEmbeddingModelObservationConvention.java, spring-ai-core/src/test/java/org/springframework/ai/chat/observation/DefaultChatModelObservationConventionTests.java, spring-ai-core/src/test/java/org/springframework/ai/embedding/observation/DefaultEmbeddingModelObservationConventionTests.java
Unlike other metrics implementations supported by Micrometer, when using the Prometheus integration, all metric attributes are supposed to have a value, or else the related metrics are dropped.
=> Keep model metric attributes fixed for Prometheus

spring-ai-core/src/main/java/org/springframework/ai/chat/client/DefaultChatClient.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/DefaultAroundAdvisorChain.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/observation/AdvisorObservationContext.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/observation/AdvisorObservationConvention.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/observation/AdvisorObservationDocumentation.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/observation/DefaultAdvisorObservationConvention.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/observation/package-info.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientInputContentObservationFilter.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientObservationContext.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientObservationConvention.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/ChatClientObservationDocumentation.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/DefaultChatClientObservationConvention.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/observation/package-info.java, spring-ai-core/src/main/java/org/springframework/ai/observation/tracing/TracingHelper.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/advisor/observation/AdvisorObservationContextTests.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/advisor/observation/DefaultAdvisorObservationConventionTests.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/ChatClientInputContentObservationFilterTests.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/ChatClientObservationContextTests.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/DefaultChatClientObservationConventionTests.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/chroma/ChromaVectorStoreAutoConfigurationIT.java
* Make ChatClient and Advisor observation logic null-safe
* Simplify naming for Advisor observations
* Include high-cardinality attributes only if a value is present
* Fix condition to include system test to chat client observations
* Add Advisor order information to context
* Streamline usage of enums and utils to reduce hard-coded/duplications
* Fix pending Chroma integration test
=> Improve chat client and advisor observations

models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientMultipleFunctionCallsIT.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/ChatClient.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/DefaultChatClient.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/DefaultChatClientBuilder.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/api/AdvisedRequest.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/ChatClientInputContentObservationFilterTests.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/ChatClientObservationContextTests.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/observation/DefaultChatClientObservationConventionTests.java
- Introduce toolContext to ChatClient, DefaultChatClient, and AdvisedRequest
- Add methods to set and manage toolContext via the FunctionCallingOptions
- Update tests to include toolContext in relevant scenarios
- Implement toolContext handling in function calling options
=> Add tool context support to ChatClient and related classes

models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiChatModel.java, models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiEmbeddingModel.java, models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureOpenAiEmbeddingModelObservationIT.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/azure/openai/AzureOpenAiAutoConfiguration.java
- Implement observation instrumentation for AzureOpenAiEmbeddingModel
- Create AzureOpenAiEmbeddingModelObservationIT for integration testing
- Update AzureOpenAiAutoConfiguration to support observation
- Introduce ObservationRegistry and observation conventions
=> Extend observation support to Azure OpenAI models

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/ollama-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/etl-pipeline.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs.adoc
* Fixes grammar in (Ollama) Function Calling.
* Fixes grammar in ETL Pipeline.
* Fixes grammar in Vector Databases.
Closes #1494
=> Cleanup grammar in documentation

spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/SafeGuardAdvisor.java
- Add customizable failure response instead of empty result
- Add order parameter for advisor prioritization
- Implement default values for failure response and order
- Introduce builder pattern for flexible configuration
Resolves #1393
=> Enhance SafeGuardAdvisor with customizable failure response

models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/BaseOllamaIT.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/ollama/BaseOllamaIT.java
* Disable tests by default
* Improve Testcontainers configuration
=> Ollama integration tests fix

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaChatModel.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaEmbeddingModel.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaModelPuller.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaOptions.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/BaseOllamaIT.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaChatModelIT.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaEmbeddingModelIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/ollama-embeddings.adoc
- Introduce internal OllamaModelPuller helper for managing model availability
- Add pullMissingModel option to OllamaOptions
- Implement auto-pull functionality in OllamaChatModel and OllamaEmbeddingModel
- Update tests to cover new auto-pull feature
- Add reference documentation
Resolves #526
=> Ollama: add model auto-pull feature

models/spring-ai-openai/README.md
I removed snapshop link in OpenAI TTS link.
- before TTS link: https://docs.spring.io/spring-ai/reference/1.0-SNAPSHOT/api/audio/speech/openai-speech.html
- after TTS link: https://docs.spring.io/spring-ai/reference/api/audio/speech/openai-speech.html
Additionally, I discovered that other links were also incorrect due to the "1.0-SNAPSHOT" keyword, so I removed the "1.0-SNAPSHOT" term from all the links.
close #1574 
Before
After
=> docs: remove "1.0-SNAPSHOT" keyword in all OpenAI links

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/mistralai-chat-functions.adoc
- Fixed broken link to test class in mistral doc
- Fixed typo in azure openai doc
=> Correction of a typo in the documentation

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/bedrock/bedrock-cohere.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/anthropic-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/azure-open-ai-chat-functions.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/vertexai-gemini-chat.adoc
- Corrected "what it" to "what is" in bedrock-cohere.adoc.
- Corrected "1st" and "supportted" to "supported" in anthropic-chat-function.adoc.
- Corrected "can some" and "can can" in azure-open-ai-chat.adoc.
- Corrected "opean" to "open" in azure-openai-chat.adoc.
- Corrected "Yur" to "Your" in azure-openai-chat.adoc.
- Corrected "o" to "on" in vertexai-gemini-chat.adoc.
=> docs: Fix Typographical Errors in spring-ai-docs

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/opensearch.adoc
This PR updates the OpenSearch documentation in the project to correctly reflect the configuration properties as defined in the code.
Related issue: https://github.com/spring-projects/spring-ai/issues/1589
=> Updated OpenSearch documentation to reflect correct configuration properties

spring-ai-docs/src/main/antora/modules/ROOT/pages/index.adoc
Updated the document title in the .adoc file to provide a descriptive title for the main page.
=> Fix HTML document title on main page to "Introduction"

pom.xml
Idk why the spring-ai-starter-azure-cosmos-db-store module is not declared
but it seems to be missing 
so adding it
=> Add spring-ai-starter-azure-cosmos-db-store submodule to pom.xml

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/milvus/MilvusVectorStoreAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/milvus/MilvusVectorStoreProperties.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/milvus/MilvusVectorStoreAutoConfigurationIT.java, vector-stores/spring-ai-milvus-store/src/main/java/org/springframework/ai/vectorstore/MilvusVectorStore.java, vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreCustomFieldNamesIT.java
- Add configuration properties to override the default field names for doc_id, content, metadata and embedding
- Add support to allow auto-id when enabled
- Add tests
Resolves #513
=> GH-513 fix: Support custom field names for Milvus VectorStore collection

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/etl-pipeline.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/imageclient.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/testing.adoc
chatclient.adoc
- Replaced javaCopySimpleLoggerAdvisor with SimpleLoggerAdvisor
- Fixed typo in the multiline String for ChatClient example
etl-pipeline.adoc
- Fixed indent in the ParagraphPdfDocumentReader example
imageclient.adoc
- Fixed indent of override annotation in the ImageGeneration example
testing.adoc
- Added a semicolon to the Evaluator interface
=> Fix example codes in docs

spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/VectorStoreChatMemoryAdvisor.java, vector-stores/spring-ai-pgvector-store/src/test/java/org/springframework/ai/vectorstore/PgVectorStoreWithChatMemoryAdvisorIT.java
The system text advise prompt is only joined with the value of the system text if it's non-null and non-empty.
=> Support case with missing system text in VectorStoreChatMemoryAdvisor

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/qianfan-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/minimax-embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/mistralai-embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/openai-embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/qianfan-embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/zhipuai-embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/image/qianfan-image.adoc
Update documentation for property override precedence in ChatModel and EmbeddingModel configurations.
=> Update property precedence in documentation

spring-ai-docs/src/main/antora/modules/ROOT/pages/index.adoc
index.adoc
Added missing Vector Database providers to the list:
- Included Elasticsearch, OpenSearch, SAP Hana, and Typesense
=> Fix Vector Database providers list

models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/BedrockConverseChatClientIT.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientProxyFunctionCallsIT.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/api/AdvisedRequest.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/advisor/api/AdvisedRequestTests.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/converse/BedrockConverseProxyChatProperties.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/bedrock/converse/BedrockConverseProxyChatPropertiesTests.java
- Add a new test case for testing function call with advisor in BedrockConverseChatClientIT
- Add a new test case for testing tool proxy function call in OpenAiChatClientProxyFunctionCallsIT
- Remove unused model property from BedrockConverseProxyChatProperties
=> Allow null or empty userText if request contains Tool Response message

models/spring-ai-bedrock-converse/src/main/java/org/springframework/ai/bedrock/converse/BedrockProxyChatModel.java, models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/api/AbstractBedrockApi.java, models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/cohere/BedrockCohereChatModelIT.java, models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/cohere/api/CohereChatBedrockApiIT.java, models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/jurassic2/BedrockAi21Jurassic2ChatModelIT.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/bedrock/converse/BedrockConverseProxyChatAutoConfiguration.java
The changes include:
- Refactor the emitting of next, error, and complete events in the Bedrock stream handling to use a default EmitFailureHandler that retries for 10 seconds before failing. This helps improve the error resilience of the stream processing.
- Disable a couple of integration tests related to the COHERE_COMMAND_V14 model, as that model version is no longer supported.
- Adjust some configuration options in the Jurassic2 chat model integration test.
Also resolves #1679
=> fix: Improve error resilience of the Bedrock stream handling

document-readers/tika-reader/pom.xml, document-readers/tika-reader/src/main/java/org/springframework/ai/reader/tika/TikaDocumentReader.java
Bump org.apache.tika from 3.0.0-BETA2 to 3.0.0
=> Bump org.apache.tika to 3.0.0

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
Commit 5aafea872dd653792e9226c1e2c409b70c4ca0e8 moved the `Media.java` file to `model` directory. This PR adjusts sources to changes.
=> Update `Message.java` reference

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaChatModel.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaChatModelTests.java
1. Resolve duplicate metadata keys when creating ChatResponseMetadata from OllamaApi.ChatResponse. 
`eval-duration` and `eval-count` were duplicated.
so they have been updated to `prompt-eval-duration` and `prompt-eval-count` to avoid overwrite.
AS-IS
TO-BE
2. Fix assertion for `ModelManagementOptions` .
AS-IS
Incorrect object was being asserted. `observationRegistry`
So, NPE occurs at line 105 where OllamaModelManager is being created.
TO-BE
Replace observationRegistry with `ModelManagementOptions`
Proper exception handling and error messages for modelManagementOptions.
=> Fix duplicate keys in ChatResponseMetadata for OllamaApi.ChatResponse

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs.adoc
The constructor of TokenCountBatchingStrategy has been modified, and the examples in the documentation have been modified accordingly.
See #1670
=> Fix TokenCountBatchingStrategy example.

models/spring-ai-bedrock-converse/src/main/java/org/springframework/ai/bedrock/converse/BedrockProxyChatModel.java, models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/BedrockConverseChatClientIT.java, models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/BedrockConverseUsageAggregationTests.java, models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/experiments/BedrockConverseChatModelMain.java, models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/experiments/BedrockConverseChatModelMain2.java, models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/experiments/BedrockConverseChatModelMain3.java, spring-ai-core/src/main/java/org/springframework/ai/model/function/FunctionCallingOptionsBuilder.java
- Replace hardcoded "tool_use" with StopReason enum value
- Add tests for token usage aggregation with tool calls
- Add handling for null response metadata
Related to #1763  - Adds requested tests
=> fix(bedrock-converse): Update tool use handling and add usage

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/function-callback.adoc
This PR fixes a typo in the documentation/code where "onn" was corrected to "on".
=> Fix typo: "onn" to "on"

models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/api/ZhiPuAiApi.java
to fix mistakenly modified in commit [fd8cac57](https://github.com/spring-projects/spring-ai/commit/fd8cac57#diff-4df7db0c9a7afc1ea8ec3caacbcf625e455796fee3a1fd35f6257d1effdf3a2bR332)
related issue: https://github.com/spring-projects/spring-ai/issues/1828
=> fix: incorrect json property annotation for ZhiPuAI

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatModel.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelIT.java
When calling the `OpenAiChatModel` with `ChatOptions`, they are always ignored. Options are considered only when using `OpenAiChatOptions` or `FunctionCallingOptions`.
This seems a regression after the recent refactoring of `FunctionCallingOptions`. I checked all the model implementation and it's only OpenAI having this error.
=> Portable ChatOptions ignored by OpenAiChatModel

spring-ai-core/src/main/java/org/springframework/ai/model/function/FunctionCallbackWrapper.java
Link was pointing to the current class.
=> fix: update deprecation link to FunctionCallback.builder()

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/chat/client/ChatClientAutoConfiguration.java
Fix the ChatClient.Builder auto-configuration so that it's only autoconfigured when there is no bean defined yet.
Fixes gh-2034
=> Do not autoconfigure ChatClient.Builder if a bean exists already

spring-ai-core/src/main/java/org/springframework/ai/vectorstore/SimpleVectorStore.java, src/checkstyle/checkstyle-suppressions.xml, vector-stores/spring-ai-azure-cosmos-db-store/src/main/java/org/springframework/ai/vectorstore/cosmosdb/CosmosDBVectorStore.java, vector-stores/spring-ai-coherence-store/src/main/java/org/springframework/ai/vectorstore/coherence/CoherenceVectorStore.java, vector-stores/spring-ai-gemfire-store/src/main/java/org/springframework/ai/vectorstore/gemfire/GemFireVectorStore.java, vector-stores/spring-ai-mongodb-atlas-store/src/main/java/org/springframework/ai/vectorstore/mongodb/atlas/MongoDBAtlasVectorStore.java, vector-stores/spring-ai-neo4j-store/src/main/java/org/springframework/ai/vectorstore/neo4j/Neo4jVectorStore.java, vector-stores/spring-ai-opensearch-store/src/main/java/org/springframework/ai/vectorstore/opensearch/OpenSearchVectorStore.java
- The VectorStore builders shouldn't be final as they are meant to be extensible
- Suppress the `FinalClass` checkstyle errors on VectorStore classes
=> Make vector store builders extensible

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/openai-chat-functions.adoc
openai-chat-functions.adoc
* Fixed indent of FunctionCallback Wrapper example
=> Fix example code indent

pom.xml
Update io.swagger.core.v3:swagger-annotations to at least version 2.2.25 to get granular schema resolution via @Schema.schemaResolution
=> Bump io.swagger.core.v3:swagger-annotations from 2.2.20 to 2.2.25

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
The o1 model is out of preview and there are new model ids, see https://platform.openai.com/docs/models#o1
=> Add o1 model to OpenAI ChatModel enum

spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/SimpleLoggerAdvisor.java
* I have observed that default response logging in simple logger advisor printing the ChatResponse in raw json. This PR changes default print method used in the simpleloggeradvisor to pretty print the response.
=> Modify SimpleLoggerAdvisor to use PrettyPrinter method for response logging

models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/api/tool/MistralAiApiToolFunctionCallIT.java
The test class contained a bug, leading to the test being deactivated. The issue has now been resolved, and the test has been reactivated to resume integration validation.
=> Resolve MistralAiApiToolFunctionCallIT issue and activate testing.

models/spring-ai-minimax/src/main/java/org/springframework/ai/minimax/api/MiniMaxApi.java
This commit adds support for the MiniMax-Text-01 model, which is recommended for general scenarios due to its longer context window. [MiniMax Chat Completion documentation](https://intl.minimaxi.com/document/ChatCompletion%20v2?key=66701d281d57f38758d581d0)
The new model is added to the ChatModel enum as MiniMax_Text_01.
=> feat(minimax): add support for MiniMax-Text-01 model

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiAudioSpeechModel.java, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiAudioTranscriptionModel.java, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiAudioApi.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/api/OpenAiAudioApiIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/audio/speech/openai-speech.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/audio/transcriptions/openai-transcriptions.adoc
- Refactor the builder methods to remove `with` as the prefix.
- Introduce new methods with updated naming conventions.
- Deprecate the existing `with*` methods to maintain backward compatibility.
=> Refactor OpenAi Audio builders

vector-stores/spring-ai-mariadb-store/src/main/java/org/springframework/ai/vectorstore/mariadb/MariaDBVectorStore.java, vector-stores/spring-ai-mariadb-store/src/test/java/org/springframework/ai/vectorstore/mariadb/MariaDBStoreIT.java
Add string-based filter deletion alongside the Filter.Expression-based deletion for MariaDB vector store, providing consistent deletion capabilities with other vector store implementations.
Key changes:
- Add delete(Filter.Expression) implementation for MariaDB store
- Integrate with existing MariaDBFilterExpressionConverter
- Add comprehensive integration tests for filter deletion
- Support both simple and complex filter expressions
This maintains consistency with other vector store implementations and enables flexible document deletion based on metadata filters.
=> Add filter-based deletion to MariaDB vector store

vector-stores/spring-ai-milvus-store/src/main/java/org/springframework/ai/vectorstore/milvus/MilvusVectorStore.java, vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/milvus/MilvusVectorStoreIT.java
Add string-based filter deletion alongside the Filter.Expression-based deletion for Milvus vector store, providing consistent deletion capabilities with other vector store implementations.
Key changes:
- Add delete(Filter.Expression) implementation for Milvus store
- Leverage existing MilvusFilterExpressionConverter for filter translation
- Use Milvus client's native delete API with filter expressions
- Add comprehensive integration tests for filter deletion
- Support both simple and complex filter expressions
This maintains consistency with other vector store implementations while utilizing Milvus-specific APIs for efficient metadata-based deletion.
=> Add filter-based deletion to Milvus vector store

vector-stores/spring-ai-typesense-store/src/main/java/org/springframework/ai/vectorstore/typesense/TypesenseVectorStore.java, vector-stores/spring-ai-typesense-store/src/test/java/org/springframework/ai/vectorstore/typesense/TypesenseVectorStoreIT.java
Add string-based filter deletion alongside the Filter.Expression-based deletion for Typesense vector store, providing consistent deletion capabilities with other vector store implementations.
Key changes:
- Add delete(Filter.Expression) implementation using Typesense filter expressions
- Leverage existing TypesenseFilterExpressionConverter for filter translation
- Use Typesense's DeleteDocumentsParameters for filtered deletion
- Add comprehensive integration tests for filter deletion
- Support both simple and complex filter expressions
This maintains consistency with other vector store implementations while utilizing Typesense's native filtering capabilities for efficient metadata-based deletion.
=> Add filter-based deletion to Typesense vector store

vector-stores/spring-ai-pinecone-store/src/main/java/org/springframework/ai/vectorstore/pinecone/PineconeVectorStore.java, vector-stores/spring-ai-pinecone-store/src/test/java/org/springframework/ai/vectorstore/pinecone/PineconeVectorStoreIT.java
Add string-based filter deletion alongside the Filter.Expression-based deletion for Pinecone vector store and improve test organization through refactoring.
Key changes:
- Add delete(Filter.Expression) implementation using two-step process:
* Search for documents matching filter
* Delete matching documents by ID
- Leverage existing search functionality to maintain filter consistency
- Extract common test patterns into helper methods
- Create reusable document factory methods for test data
- Add comprehensive integration tests for filter deletion
- Standardize test cleanup and verification patterns
This maintains consistency with other vector store implementations while working within Pinecone's API limitations. The test refactoring improves maintainability and makes the test patterns …
=> Add filter-based deletion and refactor tests for Pinecone vector store

vector-stores/spring-ai-cassandra-store/src/main/java/org/springframework/ai/vectorstore/cassandra/CassandraVectorStore.java, vector-stores/spring-ai-cassandra-store/src/test/java/org/springframework/ai/vectorstore/cassandra/CassandraVectorStoreIT.java
Implement filter-based deletion for CassandraVectorStore to support more
flexible document removal based on metadata filters.
Key changes:
- Add doDelete(Filter.Expression) implementation
- Implement workaround for Cassandra's limitations in direct filtered deletion
- Fetch matching documents first, then delete by IDs
- Add integration tests for various filter deletion scenarios
- Support simple and complex filter expressions
- Includes tests for:
* Deleting by simple equality filter
* Deleting by string-based filter expression * Deleting by complex AND filter expression
Provides consistent deletion capabilities across vector store implementations while addressing Cassandra-specific constraints.
=> Add filter-based deletion to Cassandra Vector Store

vector-stores/spring-ai-weaviate-store/src/main/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStore.java, vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreIT.java
Implement filter-based deletion for WeaviateVectorStore by leveraging the existing ID-based deletion mechanism.
Key changes:
- Add doDelete(Filter.Expression) implementation that delegates to the existing ID-based deletion method
- Use similarity search with filter to find matching documents first
- Delete matched documents by their IDs
- Add integration tests for filter deletion scenarios:
* Deleting by simple equality filter
* Deleting by string-based filter expression
This maintains consistency with other vector store implementations while working around Weaviate's limitations in direct filtered deletion.
=> Add filter-based deletion to Weaviate vector store

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/deepseek-chat.adoc
DeepSeek does not currently have an R3 model.
This appears to be a mislabeling of the V3 model.
=> Fix typo in deepseek model name in deepseek-chat.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/groq-chat.adoc
The `chat.model` property snippet was missing correct `.options` hierarchy, fixed it. Also fixed couple of spell-errors.
=> Fix spell error and updated gemma model name

models/spring-ai-ollama/pom.xml, pom.xml, spring-ai-core/pom.xml, spring-ai-docs/pom.xml, spring-ai-docs/src/main/antora/modules/ROOT/pages/upgrade-notes.adoc, spring-ai-retry/pom.xml, spring-ai-spring-boot-autoconfigure/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-oracle-store/pom.xml, spring-ai-spring-boot-testcontainers/pom.xml, vector-stores/spring-ai-cassandra-store/pom.xml, vector-stores/spring-ai-elasticsearch-store/pom.xml, vector-stores/spring-ai-elasticsearch-store/src/main/java/org/springframework/ai/vectorstore/elasticsearch/ElasticsearchVectorStore.java, vector-stores/spring-ai-opensearch-store/pom.xml, vector-stores/spring-ai-oracle-store/pom.xml, vector-stores/spring-ai-pgvector-store/pom.xml, vector-stores/spring-ai-typesense-store/pom.xml
- Spring AI's dependencies management to derive from Spring Boot 3.4.2
- Remove explicit versioning of dependencies
- Update upgrade notes for Spring Boot 3.4.2
- Fix ElasticSearch client changes with the latest dependency derived from Spring Boot 3.4.2
=> Update to Spring Boot 3.4.2 for dependency management

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaChatModel.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaChatModelTests.java, spring-ai-core/src/main/java/org/springframework/ai/model/tool/LegacyToolCallingManager.java
=> Fix handling of nullable fields in OllamaChatModel deprecated constructor

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/OllamaChatModel.java, models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaOptions.java, models/spring-ai-ollama/src/test/java/org/springframework/ai/ollama/OllamaChatRequestTests.java, spring-ai-core/src/main/java/org/springframework/ai/model/tool/ToolCallingChatOptions.java, spring-ai-core/src/test/java/org/springframework/ai/model/tool/ToolCallingChatOptionsTests.java
When fields in OllamaOptions are marked as ignored in Jackson, they require explicit merge of runtime and default options. Added tests to validate the different merge combinations for all tool-related options.
=> Add merge for missing Ollama options

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
Use proper Markdown syntax to wrap code blocks, enabling correct syntax highlighting when rendered.
=> Fix document formatting to correctly display code blocks

README.md
Fix grammatical issue in API provider documentation
- Simplify redundant wording around API provider support
- Remove duplicate terms ('support')
Before:
Portable API support across AI providers for both synchronous and streaming API options are supported.
After:
Portable API support across AI providers for both synchronous and streaming options.
=> docs: fix grammatical issue in API provider description

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/deepseek-chat.adoc
Minor doc change: fix the code indent for the sample code.
=> Fix code indent for the sample code in deepseek-chat.adoc

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/cosmosdb/CosmosDBVectorStoreAutoConfiguration.java, vector-stores/spring-ai-azure-cosmos-db-store/src/main/java/org/springframework/ai/vectorstore/cosmosdb/CosmosDBVectorStore.java
Each CosmosDBVectorStore.Builder function evaluates `this.PROPERTY_NAME` rather than the new argument passed to each function resulting in it not being possible to instantiate an instance of CosmosDBVectorStore.
=> Fix issue with CosmosDBVectorStore.Builder - "... must not be empty"

pom.xml, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/pinecone.adoc, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/pinecone/PineconeVectorStoreAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/pinecone/PineconeVectorStoreAutoConfigurationIT.java, spring-ai-test/src/main/java/org/springframework/ai/test/vectorstore/BaseVectorStoreTests.java, vector-stores/spring-ai-pinecone-store/pom.xml, vector-stores/spring-ai-pinecone-store/src/main/java/org/springframework/ai/vectorstore/pinecone/PineconeVectorStore.java, vector-stores/spring-ai-pinecone-store/src/test/java/org/springframework/ai/vectorstore/pinecone/PineconeVectorStoreIT.java, vector-stores/spring-ai-pinecone-store/src/test/java/org/springframework/ai/vectorstore/pinecone/PineconeVectorStoreObservationIT.java
- Upgrade the java client from 0.8.0 to 4.0.1
- Use io.pinecone.clients.Pinecone to setup the client configuration with the API key
- Remove projectId, environment and other deprecated client configurations
- Update upsert, delete, search operations with the new client
- Remove the projectID and Environment configurations from the builder
- Updated the Pinecone vectorstore autoconfiguration
- Update tests
=> Upgrade Pinecone java client to 4.0.1

models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/client/AnthropicChatClientMethodInvokingFunctionCallbackIT.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientMethodInvokingFunctionCallbackIT.java, spring-ai-core/src/main/java/org/springframework/ai/tool/method/MethodToolCallback.java, spring-ai-core/src/test/java/org/springframework/ai/tool/method/MethodToolCallbackTests.java
Changes the validation logic in MethodToolCallback to check if a ToolContext is required by the method but not provided, rather than checking if a ToolContext is provided but not supported by the method. This ensures methods that expect a ToolContext parameter receive one.
Updates tests cases to reflect the new validation logic
Resolves #2337
=> fix: reverse ToolContext validation logic in MethodToolCallback

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/deepseek-chat.adoc
=> correct wrong property name

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/deepseek-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/groq-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/nvidia-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/perplexity-chat.adoc
Modify how 'OpenAiChatOption','OllamaOptions'  is used
=> Modify the sample code

models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/AnthropicChatModel.java, models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/AnthropicChatOptions.java, models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/api/AnthropicApi.java, models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/AnthropicChatModelAdditionalHttpHeadersIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
Add the ability to specify custom HTTP headers for Anthropic API requests through AnthropicChatOptions. This allows users to override or add headers for authentication, tracking, or other API-specific requirements.
- Add httpHeaders field to AnthropicChatOptions with appropriate getters/setters
- Implement header merging between default and runtime options
- Update AnthropicApi to accept additional HTTP headers in API calls
- Add integration test demonstrating API key override via custom headers
- Update documentation with the new configuration property
Resolves #2335
=> feat(anthropic): add support for custom HTTP headers in Anthropic API

auto-configurations/spring-ai-mcp-client/src/main/java/org/springframework/ai/autoconfigure/mcp/client/SseHttpClientTransportAutoConfiguration.java
- fix bug @ConditionalOnMissingClass class declaration
- change from "public class WebFluxSseClientTransport" to "WebFluxSseClientTransport"
=> Fix bug SseHttpClientTransportAutoConfiguration

auto-configurations/spring-ai-mcp-server/src/main/java/org/springframework/ai/autoconfigure/mcp/server/McpServerAutoConfiguration.java, auto-configurations/spring-ai-mcp-server/src/main/java/org/springframework/ai/autoconfigure/mcp/server/McpServerProperties.java, mcp/common/src/main/java/org/springframework/ai/mcp/McpToolUtils.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
Add capability to specify MIME types for MCP tool responses, with special handling for image content.
This enhancement allows tools to return different content types, particularly images, by:
- Adding a new toolResponseMimeType map property to configure response MIME types per tool
- Extending tool registration methods to accept and use MIME type information
- Adding special handling for image content in tool responses
- Updating documentation with the new configuration options
=> feat(mcp): add support for custom MIME types in tool responses

models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/AnthropicChatOptions.java, models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/AnthropicChatOptionsTests.java
This commit enhances `AnthropicChatOptions` by:
- Adding `equals` and `hashCode` methods for proper object comparison.
- Implementing a deep `copy()` method, creating new instances of mutable collections (List, Set, Map, Metadata) to prevent shared state.
- Adding `AnthropicChatOptionsTests` to verify `copy()`, builders, setters, and default values.
=> feat: Add equals, hashCode, deep copy, and tests to AnthropicChatOptions

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
Update Anthropics Model Version in Example Code from [Documentation](https://docs.spring.io/spring-ai/reference/api/chat/anthropic-chat.html)
The legacy model is no longer supported, and attempting to use it results in an error.
The Anthropic API now returns a 404 error:
```log
org.springframework.ai.retry.NonTransientAiException: 404 - {"type":"error","error":{"type":"not_found_error","message":"model: claude-2.1"}}
```
According to the [documentation](https://docs.anthropic.com/en/docs/resources/model-deprecations), the model was scheduled for retirement on July 21, 2025. However, it appears to have already been retired.
Even if the 404 error occurs only for me, it seems there is no issue in upgrading the version since it was already deprecated on January 21, 2025.
=> update anthropic model version in example code from Documentation

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/retrieval-augmented-generation.adoc
docs: https://docs.spring.io/spring-ai/reference/api/retrieval-augmented-generation.html#_advanced_rag
- Fix typo: `queryTransformer` → `queryTransformers`
- Identified in https://github.com/spring-projects/spring-ai/issues/2296
=> fix typo in rag doc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/opensearch.adoc
docs: [spring-ai/spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/opensearch.adoc](https://github.com/spring-projects/spring-ai/blob/ff287a54573cf8330253eab8a8c3e089447b8760/spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/opensearch.adoc?plain=1#L80)
- fix typo: `List<Document> results = vectorStore.similaritySearch(SearchRequest.build().query("Spring").topK(5).build());`
-> `List<Document> results = vectorStore.similaritySearch(SearchRequest.builder().query("Spring").topK(5).build());`
- Identified in #2147
=> fix vertordbs opensearch.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/redis.adoc
Fixes #2414
resolves: https://github.com/spring-projects/spring-ai/issues/2414
Current implementation of RedisProperties: https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/RedisProperties.java#L49
=> Fix property name in Redis documentation

auto-configurations/spring-ai-mcp-server/src/main/java/org/springframework/ai/autoconfigure/mcp/server/McpServerAutoConfiguration.java, auto-configurations/spring-ai-mcp-server/src/main/java/org/springframework/ai/autoconfigure/mcp/server/McpServerProperties.java
This pull request includes fixing minor typos from `McpServerAutoConfiguration` and `McpServerProperties`.
- in `McpServerProperties`
- fixed `Optinal` to `Optional`
- in `McpServerAutoConfiguration`
- added delimiter on logging
- AS-IS: `Registered resources1 notification: true`
- TO-BE: `Registered resources: 1, notification: true`
=> Fix typo in spring-ai-mcp-server autoconfiguration

mcp/common/src/main/java/org/springframework/ai/mcp/AsyncMcpToolCallback.java, mcp/common/src/main/java/org/springframework/ai/mcp/SyncMcpToolCallback.java, mcp/common/src/test/java/org/springframework/ai/mcp/SyncMcpToolCallbackTests.java
- Implement the new ToolCallback.call(String, ToolContext) method in both Sync and Async MCP tool callbacks.
- Since MCP tools don't support tool context, the implementation ignores the context parameter and delegates to the existing call(String) method. Added test to verify the behavior.
Resolves #2378
=> feat(mcp): handle ToolContext in MCP tool callbacks

auto-configurations/spring-ai-mcp-client/src/main/java/org/springframework/ai/autoconfigure/mcp/client/McpClientAutoConfiguration.java, auto-configurations/spring-ai-mcp-client/src/main/java/org/springframework/ai/autoconfigure/mcp/client/NamedClientMcpTransport.java, auto-configurations/spring-ai-mcp-client/src/main/java/org/springframework/ai/autoconfigure/mcp/client/properties/McpStdioClientProperties.java, mcp/common/src/main/java/org/springframework/ai/mcp/AsyncMcpToolCallback.java, mcp/common/src/main/java/org/springframework/ai/mcp/SyncMcpToolCallback.java, mcp/common/src/test/java/org/springframework/ai/mcp/SyncMcpToolCallbackProviderTests.java, mcp/common/src/test/java/org/springframework/ai/mcp/SyncMcpToolCallbackTests.java
Enhances MCP tool naming by prefixing tool names with their client + transport name to prevent conflicts when multiple MCP clients expose tools with the same name.
- Modifies client info in McpClientAutoConfiguration to include transport name
- Updates SyncMcpToolCallback and AsyncMcpToolCallback to prefix tool names with client + transport name
- Adds test coverage for tools with identical names but different client info
Resolves #2393
=> feat(mcp): Prefix tool names with client name to avoid naming conflicts

mcp/common/src/main/java/org/springframework/ai/mcp/AsyncMcpToolCallback.java, mcp/common/src/main/java/org/springframework/ai/mcp/McpToolUtils.java, mcp/common/src/main/java/org/springframework/ai/mcp/SyncMcpToolCallback.java, mcp/common/src/test/java/org/springframework/ai/mcp/SyncMcpToolCallbackTests.java
- Add prefixedToolName utility method to ensure consistent tool name formatting
- Enforce alphanumeric, underscore, and hyphen characters only in tool names
- Limit tool names to 64 characters maximum
- Use original tool name in actual calls while using formatted names in definitions
- Add error handling for tool call responses in SyncMcpToolCallback
- Update tests to reflect the changes
Resolves issues introduced by #2436
=> fix(mcp): standardize MCP tool name formatting and improve error handle

auto-configurations/spring-ai-mcp-client/src/main/java/org/springframework/ai/autoconfigure/mcp/client/SseHttpClientTransportAutoConfiguration.java, auto-configurations/spring-ai-mcp-client/src/main/java/org/springframework/ai/autoconfigure/mcp/client/SseWebFluxTransportAutoConfiguration.java
Replace direct dependencies with ObjectProvider pattern in SSE transport auto-configurations.
- Uses ObjectProvider for ObjectMapper and WebClient.Builder dependencies
- Removes redundant @ConditionalOnMissingBean methods
- Provides fallback instantiation when dependencies are not available
Resolves #2440
=> refactor: replace direct dependencies with ObjectProvider in MCP

spring-ai-core/src/main/java/org/springframework/ai/tool/ToolCallbackProvider.java
Motivication:
Remove unnecessary public modifier in ToolCallbackProvider.
=> chore: Remove unnecessary public modifier in ToolCallbackProvider.

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
Existing code for **Runtime Options** displays a typo where the model is `gpt-4-o` and should be `gpt-4o`:
```
ChatResponse response = chatModel.call(
new Prompt(
"Generate the names of 5 famous pirates.",
OpenAiChatOptions.builder()
.model("gpt-4-o")
.temperature(0.4)
.build()
));
```
Using `gpt-4-o` generates this error:
```
org.springframework.ai.retry.NonTransientAiException: 404 - {
"error": {
"message": "The model `gpt-4-o` does not exist or you do not have access to it.",
"type": "invalid_request_error",
"param": null,
"code": "model_not_found"
}
}
```
Changing the `model` parameter in the example to `gpt-4o` resolves this.
* …
=> Typo in example code

auto-configurations/spring-ai-mcp-client/src/test/java/org/springframework/ai/autoconfigure/mcp/client/SseHttpClientTransportAutoConfigurationTests.java, auto-configurations/spring-ai-mcp-client/src/test/java/org/springframework/ai/autoconfigure/mcp/client/SseWebFluxTransportAutoConfigurationTests.java
- Add SseHttpClientTransportAutoConfigurationTests to verify conditional bean creation for HTTP client transports
- Add SseWebFluxTransportAutoConfigurationTests to verify conditional bean creation for WebFlux client transports
- Test both auto-configurations with various conditions including presence/absence of WebFluxSseClientTransport and MCP client enabled/disabled states
=> Add condition tests for MCP client transport auto-configurations

spring-ai-core/src/main/java/org/springframework/ai/embedding/AbstractEmbeddingModel.java, spring-ai-core/src/main/java/org/springframework/ai/embedding/Embedding.java, spring-ai-core/src/main/java/org/springframework/ai/embedding/EmbeddingResultMetadata.java
- Fix Embedding equals() using Arrays.equals() for embedding array comparison
- Fix Embedding hashCode() using Arrays.hashCode() for proper array hashing
- Add final modifiers to fields in Embedding classes
=> Fix array comparison and add final modifiers in embedding classes

spring-ai-core/src/main/java/org/springframework/ai/tool/method/MethodToolCallbackProvider.java, spring-ai-core/src/test/java/org/springframework/ai/tool/method/MethodToolCallbackProviderAopTests.java, spring-ai-core/src/test/java/org/springframework/ai/tool/method/MethodToolCallbackProviderTests.java, spring-ai-core/src/test/java/org/springframework/ai/tool/method/MethodToolCallbackTests.java
This change ensures that @Tool annotated methods can be properly discovered even when the tool objects are wrapped in Spring AOP proxies, which is common when using aspects or other proxy-based features.
- Enhance MethodToolCallbackProvider to properly handle AOP proxied tool objects by detecting proxies and retrieving their target classes when scanning for @Tool annotated methods.
- Add test suite in MethodToolCallbackProviderAopTests.java to verify AOP proxy handling
Resolves #2356
=> feat: Add AOP proxy support to MethodToolCallbackProvider

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiEmbeddingModel.java
The issue described in https://github.com/spring-projects/spring-ai/issues/2485, where a NullPointerException (NPE) occurs when the `usage` field is null in OpenAI-compatible models, has been fixed.
=> allow null usage for OpenAI embedding model

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatModel.java
optimize: use already defined variables
=> optimize: use already defined variables

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
Original:
ChatOptions chatOptions = ToolCallingChatOptions.builder()
.toolCallbacks(customerTools)
.toolContext(Map.of("tenantId", "acme"))
.build():
After Change:
ChatOptions chatOptions = ToolCallingChatOptions.builder()
.toolCallbacks(customerTools)
.toolContext(Map.of("tenantId", "acme"))
.build();
=> Update tools.adoc Corrected incorrect punctuation usage

auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-couchbase/pom.xml, auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-couchbase/src/main/java/org/springframework/ai/vectorstore/couchbase/autoconfigure/CouchbaseSearchVectorStoreAutoConfiguration.java, auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-couchbase/src/main/java/org/springframework/ai/vectorstore/couchbase/autoconfigure/CouchbaseSearchVectorStoreProperties.java, auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-couchbase/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-couchbase/src/test/java/org/springframework/ai/vectorstore/couchbase/autoconfigure/CouchbaseContainerMetadata.java, auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-couchbase/src/test/java/org/springframework/ai/vectorstore/couchbase/autoconfigure/CouchbaseSearchVectorStoreAutoConfigurationIT.java, pom.xml, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/couchbase.adoc, spring-ai-spring-boot-starters/spring-ai-starter-vector-store-couchbase/pom.xml
- Update dependencies and module names in maven pom.xml files affecting couchbase vector store support
- Rename artifact from spring-ai-couchbase-store-spring-boot-starter to spring-ai-starter-vector-store-couchbase
- Update imports and related cleanup
- Update corresponding documentation references
=> Migrate Couchbase vector store auto-configuration to dedicated module

auto-configurations/models/spring-ai-autoconfigure-model-ollama/pom.xml, auto-configurations/models/spring-ai-autoconfigure-model-ollama/src/test/java/org/springframework/ai/model/ollama/autoconfigure/OllamaChatAutoConfigurationIT.java, auto-configurations/models/spring-ai-autoconfigure-model-ollama/src/test/java/org/springframework/ai/model/ollama/autoconfigure/OllamaEmbeddingAutoConfigurationIT.java, auto-configurations/models/spring-ai-autoconfigure-model-ollama/src/test/kotlin/org/springframework/ai/model/ollama/autoconfigure/tool/FunctionCallbackContextKotlinIT.kt
- Add missing jackson-module-kotlin for the kotlin tests
- Fix Function calling options to use ToolCallingChatOptions
=> Fix Ollam test configuration

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/retrieval-augmented-generation.adoc
Hello Spring AI Team,
This PR fixes a broken xref link that did not correctly resolve to the intended documentation section. 
The link is now updated to correctly point to the published HTML page.
=> Fix :: Broken URL link to document

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/structured-output-converter.adoc
Hello Spring AI Team,
This PR fixes the deprecated getContent to getText in the Structured Output Converter documentation.
=> Fix Structured Output Converter docs

auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-redis/src/main/java/org/springframework/ai/vectorstore/redis/autoconfigure/RedisVectorStoreAutoConfiguration.java, auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-redis/src/main/java/org/springframework/ai/vectorstore/redis/autoconfigure/RedisVectorStoreProperties.java, auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-redis/src/test/java/org/springframework/ai/vectorstore/redis/autoconfigure/RedisVectorStorePropertiesTests.java
The [documentation](https://docs.spring.io/spring-ai/reference/api/vectordbs/redis.html) states that the index name can be configured using `index-name`, but it was actually configured using `index`.
This has now been corrected to use `index-name`.
=> Refactor Redis vector store property: index to indexName

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatmodel.adoc
Hello Spring AI Team,
This PR fixes the deprecated `getContent()` to `getText()` in the ChatModel documentation.
=> Fix ChatModel docs

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/multimodality.adoc
fix BakLLaVA model name spelling in multimodality documentation
=> docs: fix BakLLaVA model name spelling in multimodality documentation

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs.adoc
(Fixes #2562)
I noticed a duplicate example in the Vector Databases documentation. In the section about filter operators (IN, NIN, NOT), the example shown is identical to an earlier example and doesn't actually demonstrate these operators.
Replace the duplicate example with one that properly demonstrates the IN, NOT, and other operators:
```java
Expression exp = b.and(b.in("genre", "drama", "documentary"), b.not(b.lt("year", 2020))).build();
=> Fix: Duplicate example in Vector Databases documentation

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/elasticsearch.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/neo4j.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/opensearch.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/pgvector.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/qdrant.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/redis.adoc
Update vectordbs doc,batching-strategy is remove
=> Update vectordbs doc,batching-strategy is remove

auto-configurations/models/tool/spring-ai-autoconfigure-model-tool/src/test/java/org/springframework/ai/model/tool/autoconfigure/ToolCallingAutoConfigurationTests.java
=> fix typo in ToolCallingAutoConfigurationTests

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/openai-chat-functions.adoc
Small PR - Commit 1e3eaec7b9d853e399cb370dfd63e05ccee193ca moved `OpenAiApiToolFunctionCallIT.java`. This PR adjusts sources to changes. Relevant page: https://docs.spring.io/spring-ai/reference/api/chat/functions/openai-chat-functions.html
=> Update `OpenAiApiToolFunctionCallIT` source

auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/aot/McpClientAutoConfigurationRuntimeHints.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/resources/META-INF/spring/aot.factories, auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/McpClientAutoConfigurationRuntimeHintsTests.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/resources/nested/nested-config.json, auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/resources/test-config.json
Fixes: https://github.com/spring-projects/spring-ai/issues/2633
- Create McpClientAutoConfigurationRuntimeHints class
- Implement registerHints method to support JSON resources
- Add test class with comprehensive assertions
- Update aot.factories to register the new runtime hints
- Add sample JSON configuration files for testing
=> GH-2633: MCP client autoconfiguration runtime hints

pom.xml, spring-ai-bom/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-model-chat-memory-cassandra/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-model-chat-memory-neo4j/pom.xml
Also, create new memory chat starters for cassandra and neo4j.
Fixes #2709
Signed-off-by: Eddú Meléndez <eddu.melendez@gmail.com>
=> Add missing chat memory entries to BOM

models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/MergeUtils.java, pom.xml
Adjust MergeUtils to accommodate API changes:
- Update ChatCompletions constructor parameter list to remove the usage argument
- Move usage assignment to post-construction via reflection
=> Upgrade azure-open-ai-client to 1.0.0-beta.16

pom.xml, spring-ai-bom/pom.xml, spring-ai-client-chat/src/test/java/org/springframework/ai/prompt/PromptTemplateTest.java, spring-ai-client-chat/src/test/java/org/springframework/ai/prompt/PromptTests.java, spring-ai-commons/src/main/java/org/springframework/ai/template/NoOpTemplateRenderer.java, spring-ai-commons/src/main/java/org/springframework/ai/template/TemplateRenderer.java, spring-ai-commons/src/main/java/org/springframework/ai/template/ValidationMode.java, spring-ai-commons/src/test/java/org/springframework/ai/template/NoOpTemplateRendererTests.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/upgrade-notes.adoc, spring-ai-model/pom.xml, spring-ai-model/src/main/java/org/springframework/ai/chat/prompt/PromptTemplate.java, spring-ai-model/src/main/java/org/springframework/ai/chat/prompt/TemplateFormat.java, spring-ai-model/src/main/java/org/springframework/ai/template/TemplateRenderer.java, spring-ai-model/src/test/java/org/springframework/ai/chat/prompt/PromptTemplateTests.java, spring-ai-template-st/pom.xml, spring-ai-template-st/src/main/java/org/springframework/ai/template/st/StTemplateRenderer.java, spring-ai-template-st/src/test/java/org/springframework/ai/template/st/StTemplateRendererTests.java
- Introduce new TemplateRenderer API providing the logic for rendering an input template.
- Update the PromptTemplate API to accept a TemplateRenderer object at construction time.
- Move ST logic to StTemplateRenderer implementation, used by default in PromptTemplate. Additionally, make start and end delimiter character configurable.
Relates to gh-2655, gh-1687.
Second PR will follow to use TemplateRenderer in ChatClient. See usage examples here: https://github.com/ThomasVitale/spring-ai/pull/1/files#diff-38f2fe47de01515938c5201ff9af94a7fa869b2760c515e2472f83cb42271518R103
=> Introduce TemplateRenderer for prompt templating

spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/observation/DefaultChatClientObservationConvention.java, spring-ai-client-chat/src/test/java/org/springframework/ai/chat/client/observation/DefaultChatClientObservationConventionTests.java
The DefaultChatClientObservationConvention is now not removing entries from the observation context, resulting in advisor context entries being removed in the ChatClientRequest.
Fixes gh-2876
=> Fix mutable observation context

models/spring-ai-oci-genai/src/main/java/org/springframework/ai/oci/cohere/OCICohereChatOptions.java, models/spring-ai-oci-genai/src/test/java/org/springframework/ai/oci/cohere/OCICohereChatOptionsTests.java
This commit enhances OCICohereChatOptions by:
- Updating equals and hashCode methods for proper object comparison.
- Updating copy() method, creating new instances of mutable collections (List, Set, Map, Metadata) to prevent shared state.
- Adding OCICohereChatOptionsTests to verify copy(), builders, setters, and default values.
=> feat: Add equals, hashCode, deep copy, and tests to OCICohereChatOptions

auto-configurations/models/chat/memory/spring-ai-autoconfigure-model-chat-memory-cassandra/src/test/java/org/springframework/ai/model/chat/memory/cassandra/autoconfigure/CassandraChatMemoryAutoConfigurationIT.java, auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-cassandra/src/test/java/org/springframework/ai/vectorstore/cassandra/autoconfigure/CassandraVectorStoreAutoConfigurationIT.java, memory/spring-ai-model-chat-memory-cassandra/src/test/java/org/springframework/ai/chat/memory/cassandra/CassandraChatMemoryIT.java, vector-stores/spring-ai-cassandra-store/src/test/java/org/springframework/ai/vectorstore/cassandra/CassandraRichSchemaVectorStoreIT.java, vector-stores/spring-ai-cassandra-store/src/test/java/org/springframework/ai/vectorstore/cassandra/CassandraVectorStoreIT.java, vector-stores/spring-ai-cassandra-store/src/test/java/org/springframework/ai/vectorstore/cassandra/CassandraVectorStoreObservationIT.java
`org.testcontainers.containers.CassandraContainer` is deprecated.
Signed-off-by: Eddú Meléndez <eddu.melendez@gmail.com>
=> Switch CassandraContainer implementation

vector-stores/spring-ai-cassandra-store/src/main/java/org/springframework/ai/vectorstore/cassandra/CassandraVectorStore.java
Updated the `Preconditions.checkState` call to include `this.schema.table` as an argument.
#2837
=> Fix missing table name in exception message in CassandraVectorStore

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/openai-embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/usage-handling.adoc
Fixes GH-2743 (https://github.com/spring-projects/spring-ai/issues/2743)
Revised the following files to ensure accuracy:
- `openai-chat.adoc`
- `openai-embeddings.adoc`
- `usage-handling.adoc`
Fixes #2743
=> GH-2743: Correct erroneous content in documents

auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/StdioTransportAutoConfiguration.java
fix typos in stdio variable names (sdio -> stdio) 🧹
=> fix(mcp): fix stdio typos in variable names

mcp/common/src/main/java/org/springframework/ai/mcp/SyncMcpToolCallbackProvider.java
Motivation:
Use stream flatmap to make code a little clean.
=> chore: Use stream flatmap when build toolcallbacks.

auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/SseHttpClientTransportAutoConfiguration.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/SseWebFluxTransportAutoConfiguration.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/properties/McpSseClientProperties.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/SseHttpClientTransportAutoConfigurationTests.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/SseWebFluxTransportAutoConfigurationTests.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/properties/McpClientCommonPropertiesTests.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/test/java/org/springframework/ai/mcp/client/autoconfigure/properties/McpSseClientPropertiesTests.java
Enhance MCP client transports with configurable SSE endpoint support:
- Add sseEndpoint parameter to SseParameters record
- Update HttpClientSseClientTransport to use builder pattern with sseEndpoint support
- Update WebFluxSseClientTransport to use builder pattern with sseEndpoint support
- Set default SSE endpoint to /sse when not explicitly configured
- Add tests for MCP client properties
- Enhance MCP client transport tests and refactor config
=> feat(mcp): Add configurable SSE endpoint support for MCP client transports

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat-memory.adoc
This pull request updates the example in chat-memory.adoc where ChatMemory was incorrectly initialized using MessageChatMemoryAdvisor.builder().build().
It has been corrected to use MessageWindowChatMemory.builder().build() as intended.
=> Fix incorrect ChatMemory initialization example in chat-memory.adoc

spring-ai-model/src/main/java/org/springframework/ai/chat/metadata/DefaultUsage.java
Remove not existing `generationTokens` parameter from `DefaultUsage.java`
=> Fix: Remove nonexisting parameter from javadoc

auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfiguration.java, pom.xml
- Re-enables completionspec features in MCP server by uncommenting previously commented code
- Updates MCP SDK version to 0.10.0-SNAPSHOT to support these features
=> Re-enable completionspec features in MCP server

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaApi.java
This update enables deserialization of the 'capabilities' field from the JSON response.
[Ollama Show Model Information](https://github.com/ollama/ollama/blob/main/docs/api.md#show-model-information)
=> Add 'capabilities' field to ShowModelResponse in OllamaApi

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
IntelliJ couldn't find `spring-ai-starter-mcp-server` artifactId even, when I added Spring repositories
```
<repositories>
<repository>
<id>spring-milestones</id>
<name>Spring Milestones</name>
<url>https://repo.spring.io/milestone</url>
<snapshots>
<enabled>false</enabled>
</snapshots>
</repository>
<repository>
<id>spring-snapshots</id>
<name>Spring Snapshots</name>
<url>https://repo.spring.io/snapshot</url>
<releases>
<enabled>false</enabled>
</releases>
</repository>
</repositories>
```
I guess the artifactId has been changed overtime to `spring-ai-mcp-server-spring-boot-starter` and it's available in MVN Repository: https://mvnrepository.com/artifact/org.springframework.ai/spring-ai-mcp-server-spring-boot-starter/1.0.0-M6
=> Fix incorrect artifactId

pom.xml
Milvus from 2.5.7 to 2.5.8
Solved the following error:
java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3.isStringEmpty(java.lang.Object)' 
at io.milvus.grpc.ClientInfo.getSerializedSize(ClientInfo.java:402) ~[milvus-sdk-java-2.5.7.jar:na] 
at com.google.protobuf.CodedOutputStream.computeMessageSizeNoTag(CodedOutputStream.java:916) ~[protobuf-java-3.6.1.jar:na] 
at com.google.protobuf.CodedOutputStream.computeMessageSize(CodedOutputStream.java:668) ~[protobuf-java-3.6.1.jar:na] 
at io.milvus.grpc.ConnectRequest.getSerializedSize(ConnectRequest.java:129) ~[milvus-sdk-java-2.5.7.jar:na] 
at io.grpc.protobuf.lite.ProtoInputStream.available(ProtoInputStream.java:108) ~[grpc-protobuf-lite-1.59.1.jar:1.59.1] 
at …
=> Update dependencies for milvus stores

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/neo4j.adoc
Update the documentation of spring property from `spring.ai.vectorstore.neo4j.dimensions` to `spring.ai.vectorstore.neo4j.embedding-dimension`  to reflect what the code reads.  Without this change, changes to the property `dimensions` are not propagated to runtime code, resulting in discrepancies if an embedding model that has  a different number of dimensions is used
See backign configuration property in the builder at https://github.com/spring-projects/spring-ai/blob/main/vector-stores/spring-ai-neo4j-store/src/main/java/org/springframework/ai/vectorstore/neo4j/Neo4jVectorStore.java#L453
* Sign the [contributor license …
=> Update neo4j.adoc - change `spring.ai.vectorstore.neo4j.dimensions` to `spring.ai.vectorstore.neo4j.embedding-dimension` 

auto-configurations/models/spring-ai-autoconfigure-model-openai/src/main/java/org/springframework/ai/model/openai/autoconfigure/OpenAiImageAutoConfiguration.java, auto-configurations/models/spring-ai-autoconfigure-model-openai/src/main/java/org/springframework/ai/model/openai/autoconfigure/OpenAiImageProperties.java, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiImageApi.java
rel issue: https://github.com/spring-projects/spring-ai/issues/3113
=> OpenAiImageModel support configure imagesPath

vector-stores/spring-ai-mariadb-store/src/test/java/org/springframework/ai/vectorstore/mariadb/MariaDBStoreCustomNamesIT.java
`MariaDBStoreCustomNamesIT.java` requires the `OPENAI_API_KEY` system environment variable.
https://github.com/spring-projects/spring-ai/blob/5a40ac074489a2e6d69f175b7fa523c476f12435/vector-stores/spring-ai-mariadb-store/src/test/java/org/springframework/ai/vectorstore/mariadb/MariaDBStoreCustomNamesIT.java#L256-L258
However, it lacks the `@EnabledIfEnvironmentVariable` annotation, causing the test to fail.
I have added the annotation to resolve this issue.
=> Add EnabledIfEnvironmentVariable annotation to MariaDBStoreCustomNamesIT

auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-opensearch/src/main/java/org/springframework/ai/vectorstore/opensearch/autoconfigure/OpenSearchVectorStoreProperties.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/opensearch.adoc
=> Updated docs for new OpenSearch vector-store properties

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/moderation/openai-moderation.adoc
Fix typo in openai-moderation.doc
=> Docs: Fix typo in openai-moderation.doc

vector-stores/spring-ai-qdrant-store/src/main/java/org/springframework/ai/vectorstore/qdrant/QdrantValueFactory.java, vector-stores/spring-ai-qdrant-store/src/test/java/org/springframework/ai/vectorstore/qdrant/QdrantVectorStoreIT.java
- Fix the QdrantValueFactory to handle "java.util.List" type
- Update the integration test to use List type values
Resolves #3164
=> Fix qdrant vector store value factory

.github/workflows/continuous-inspection.yml, .github/workflows/continuous-integration.yml, .github/workflows/deploy-docs.yml, .github/workflows/pr-check.yml
GHA workflows are automatically executed on forks where they fail. This change prevents this (only for those workflows that are automatically triggered, e.g.: on push or schedule).
=> Do not trigger GHA workflows on forks

auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfiguration.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpServerProperties.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/test/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfigurationIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
- Add capability configuration to enable/disable tools, resources, prompts, and completions individually
- Refactor server configuration to conditionally register capabilities based on configuration
- Add support for server instructions configuration
- Update documentation with new capability options and completion management
- Add tests for new capabilities and configurations
Resolves #3207
=> feat(mcp): Add granular control over MCP server capabilities

document-readers/jsoup-reader/pom.xml, document-readers/markdown-reader/pom.xml, document-readers/pdf-reader/pom.xml, document-readers/tika-reader/pom.xml, mcp/common/pom.xml, memory/repository/spring-ai-model-chat-memory-repository-cassandra/pom.xml, memory/repository/spring-ai-model-chat-memory-repository-neo4j/pom.xml, models/spring-ai-anthropic/pom.xml, models/spring-ai-azure-openai/pom.xml, models/spring-ai-bedrock-converse/pom.xml, models/spring-ai-bedrock/pom.xml, models/spring-ai-deepseek/pom.xml, models/spring-ai-huggingface/pom.xml, models/spring-ai-minimax/pom.xml, models/spring-ai-mistral-ai/pom.xml, models/spring-ai-oci-genai/pom.xml, models/spring-ai-ollama/pom.xml, models/spring-ai-openai/pom.xml, models/spring-ai-postgresml/pom.xml, models/spring-ai-stability-ai/pom.xml, models/spring-ai-transformers/pom.xml, models/spring-ai-vertex-ai-embedding/pom.xml, models/spring-ai-vertex-ai-gemini/pom.xml, models/spring-ai-zhipuai/pom.xml, spring-ai-retry/pom.xml
Replace spring-ai-client-chat dependency with spring-ai-model in model implementations and memory repositories, and with spring-ai-commons in document readers. This change improves the dependency structure by having components depend on the appropriate abstraction level.
Additional changes:
- Add slf4j-api dependency to pdf-reader and spring-ai-retry
- Move spring-ai-client-chat to test scope in spring-ai-ollama
- Fix XML formatting in some pom.xml files
=> refactor: update dependencies to use spring-ai-model and spring-ai-commons

spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/observation/ChatClientPromptContentObservationHandler.java, spring-ai-client-chat/src/test/java/org/springframework/ai/chat/client/observation/ChatClientPromptContentObservationHandlerTests.java, spring-ai-model/src/main/java/org/springframework/ai/chat/observation/ChatModelCompletionObservationHandler.java, spring-ai-model/src/main/java/org/springframework/ai/chat/observation/ChatModelPromptContentObservationHandler.java, spring-ai-model/src/main/java/org/springframework/ai/image/observation/ImageModelPromptContentObservationHandler.java, spring-ai-model/src/test/java/org/springframework/ai/chat/observation/ChatModelCompletionObservationHandlerTests.java, spring-ai-model/src/test/java/org/springframework/ai/chat/observation/ChatModelPromptContentObservationHandlerTests.java, spring-ai-model/src/test/java/org/springframework/ai/image/observation/ImageModelPromptContentObservationHandlerTests.java, spring-ai-vector-store/src/main/java/org/springframework/ai/vectorstore/observation/VectorStoreQueryResponseObservationHandler.java, spring-ai-vector-store/src/test/java/org/springframework/ai/vectorstore/observation/VectorStoreQueryResponseObservationHandlerTests.java
The features are disabled by default and users need to explicitly enable them. Probably it makes more sense to log on INFO level so that users don't need to change the log level if they use the default behavior of Spring Boot.
See gh-3003
See gh-3127
=> Change log level from DEBUG to INFO for ObservationHandlers

auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfiguration.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/main/java/org/springframework/ai/mcp/server/autoconfigure/McpServerProperties.java, auto-configurations/mcp/spring-ai-autoconfigure-mcp-server/src/test/java/org/springframework/ai/mcp/server/autoconfigure/McpServerAutoConfigurationIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
Add support for configuring request timeout in MCP server with a default of 20 seconds. This timeout applies to all requests made through the client, including tool calls, resource access, and prompt operations.
- Add requestTimeout property to McpServerProperties with default of 20s
- Configure server builder with the timeout value
- Add tests for default and custom timeout configurations
- Update documentation with the new property
Resolves #3205
=> feat(mcp): Add request timeout configuration for MCP server

spring-ai-docs/src/main/antora/modules/ROOT/nav.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
- Update Observability section with details about tool calling observability support
- Move "Migrating to ToolCallback API" guide from Tool Calling section to Upgrade Notes
- Update Observability section with details about tool calling observability support
Related to #3230
=> docs: reorganize tool calling documentation and add observability

auto-configurations/mcp/spring-ai-autoconfigure-mcp-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/McpToolCallbackAutoConfiguration.java
Currently, the MCP Tool autoconfiguration defines the `SyncMcpToolCallbackProvider` and `AsyncMcpToolCallbackProvider` beans returning the `ToolCallbackProvider` interface. That generates autowiring warnings in IDEs when trying to inject the specific class.
The Spring Boot project recommends being specific:
> When declaring a @Bean method, provide as much type information as possible in the method’s return type. For example, if your bean’s concrete class implements an interface the bean method’s return type should be the concrete class and not the interface. Providing as much type information as possible in @Bean methods is particularly important when using bean conditions as their evaluation can only rely upon to type information that is available in the method signature.
See …
=> MCP ToolCallbackProvider autoconfig should use concrete class

memory/repository/spring-ai-model-chat-memory-repository-jdbc/src/main/java/org/springframework/ai/chat/memory/repository/jdbc/JdbcChatMemoryRepositoryDialect.java
Fixes #3281 
- Updated `from` method in `JdbcChatMemoryRepositoryDialect` to use try with resources to safely access and close the datasource connection
=> Fix datasource connection leak when using the JdbcChatMemoryRepository

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/effective-agents.adoc
This pull request fixes incorrect external link formatting in the `effective-agents.adoc` documentation file.
The following broken or misformatted links were corrected:
- `evaluator-optimizer`
- `orchestrator-workers`
These changes ensure that readers are directed to the correct external resources.
Note: The `parallelization-workflow` link was broken due to a typo in the example project's directory name.  
This has been fixed in the related example project: https://github.com/spring-projects/spring-ai-examples/pull/42 
cc @tzolov
=> Fix incorrect external link formatting in effective-agents.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
I updated project from 1.0.0-M7 to 1.0.0 and noticed I should be using `toolNames` instead of `tools`. See [commit](https://github.com/eddumelendez/spring-ai-dmr/commit/7830892df4bf179991d7ad4dc03115893e723ad9)
=> Fix tools docs

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
Fix outdated OpenAiChatClient usage in openai-api.adoc
=> docs: update custom API key example using OpenAiChatModel.builder()

README.md, spring-ai-docs/src/main/antora/modules/ROOT/pages/getting-started.adoc
This pull request updates the link to the awesome-spring-ai project.
The previous link (https://github.com/danvega/awesome-spring-ai) has been replaced with the official repository:
https://github.com/spring-ai-community/awesome-spring-ai
=> Fix awesome-spring-ai link to official repository

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/mistralai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
The class `Media.java` has been moved in 69d5b5fc and d45ff8e9.
There are 6 links in the documentation that point to the source code of this class in GitHub but haven't been updated. They currently yield a "page not found" error when clicked. For example in this section: https://docs.spring.io/spring-ai/reference/api/chat/azure-openai-chat.html#_multimodal
The PR fixes the links with the correct one: https://github.com/spring-projects/spring-ai/blob/main/spring-ai-commons/src/main/java/org/springframework/ai/content/Media.java
=> Fix links in documentation to `Media.java`

CONTRIBUTING.adoc
- This PR fixes a minor typo in the CONTRIBUTING.adoc file.
- Replaced the word 'synch' with the more commonly accepted spelling 'sync' to improve clarity and consistency in the documentation.
=> docs: fix typo 'synch' to 'sync' in CONTRIBUTING.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
The `ToolContext` does not have a `get(String)` method. This PR is fixing the documentation to show the methods that can be used.
However, I think that it would be better if `ToolContext` had a `get(String)` method that would look like:
```java
public Object get(String key) {
return this.context.get(key);
}
```
It could also be made generic:
```java
public <T> T get(String key) {
return (T) this.context.get(key);
}
```
If you prefer to add the method, I can go ahead and create a PR for that instead
=> Fix CustomerTools example to use existing methods

document-readers/pdf-reader/src/main/java/org/springframework/ai/reader/pdf/config/ParagraphManager.java
Added a simple null check to avoid looping through all the page tree if currentPage is null and there is nothing to be found
=> Avoid looping through all the page tree if there is no destination page

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/elasticsearch.adoc
add description of embedding-field-name property in elasticsearch.adoc
`embedding-field-name` property was implemented in https://github.com/spring-projects/spring-ai/pull/2175
However, the documentation had no explanation. So it was added in this PR.
---
please close https://github.com/spring-projects/spring-ai/issues/2082.
=> docs: add description of embedding-field-name property in elasticsearch.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/bedrock-converse.adoc
This update enhances the clarity and correctness of the documentation in the Nova video modalities section. Key changes include:
- Corrected the MIME type for video/x-matroska (was previously shown as video/x-matros).
- fixed few mime types.
- Use videos instead of images while referring to video mime types.
=> docs(bedrock-converse): fix MIME types and standardize formatting

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
**Problem:**  
In the current documentation or code samples, `ToolDefinition.builder(method)` is used to build a ToolDefinition from a `Method`. However, `ToolDefinition` does not have such a static builder method that accepts a `Method` — this causes confusion and runtime errors.
**Correct Usage:**  
It should be `ToolDefinitions.builder(method)` (note the plural form), as defined in the Spring AI tooling API.
**Suggested Fix:**  
Update all references of `ToolDefinition.builder(method)` to `ToolDefinitions.builder(method)` in documentation or samples.
**Version:** Spring AI 1.0.0
Thanks for your awesome work!
I may be wrong here, and if this was intentional, feel free to close the PR.
Just wanted to help improve the docs and avoid confusion for others.  Thanks again!
=> fix: correct ToolDefinition.builder() usage in docs

auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-chroma/src/main/java/org/springframework/ai/vectorstore/chroma/autoconfigure/ChromaVectorStoreAutoConfiguration.java
Fixes #3427 
Added the missing databaseName and tenantName properties in the AutoConfiguration of ChromaVectorStore.
=> Fixed the missing properties in the AutoConfiguration of ChromaVectorStore

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiAudioApi.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/audio/speech/OpenAiSpeechModelIT.java
- Updated Javadoc and voice list in `OpenAiAudioApi.java` to reflect latest [OpenAI-supported TTS voices](https://platform.openai.com/docs/api-reference/audio/createSpeech#audio-createspeech-voice).
- Synced voice options in `OpenAiApi.java` to ensure consistency for audio output generation [Openai chat completion](https://platform.openai.com/docs/api-reference/chat/create#chat-create-audio).
- Enhanced integration test `OpenAiSpeechModelIT.java` by adding new voice cases via ValueSource for better coverage.
=> feat(openai): for tts and chat completions update supported voices enums

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/huggingface.adoc
- Corrected the mistakenly added content in PR https://github.com/spring-projects/spring-ai/pull/2570.
- `spring.ai.model.chat (Removed and no longer valid)` → `spring.ai.model.chat`
- Modified the code to avoid using removed methods related to the response.
- `response.getGeneration().getResult().getOutput().getContent()` → `response.getResult().getOutput().getText()`
=> docs: update huggingface doc

spring-ai-model/src/main/java/org/springframework/ai/chat/metadata/ChatGenerationMetadata.java
- Changed the parameter name in the finishReason method from 'id' to 'finishReason' for better clarity and accuracy
=> refactor(spring-ai-model): improve parameter name in ChatGenerationMetadata

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/deepseek-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/dmr-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/groq-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/minimax-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/mistralai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/nvidia-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/perplexity-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/vertexai-gemini-chat.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/zhipuai-chat.adoc
- Updated documentation to correct broken hyperlinks to ChatOptions and its builder() method.
- Replaced the reference to the now-removed ChatOptionsBuilder with DefaultChatOptionsBuilder, which is the current default implementation of the ChatOptions.Builder interface.
=> docs(web): fix broken links to ChatOptions and ChatOptions#builder()

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
**📄 Documentation Bug**
**Problem:**
#3486 
In the 1.0.0 version of the documentation, the Vision example shown is actually from version 1.1.0-SNAPSHOT. Shouldn't the example below be included instead if it's truly the 1.0.0 documentation?
**Suggested Fix:**
Update OpenAI page Vision section
**Version:** Spring AI 1.0.0
=> docs: update OpenAI page Vision section

auto-configurations/models/tool/spring-ai-autoconfigure-model-tool/src/main/java/org/springframework/ai/model/tool/autoconfigure/ToolCallingProperties.java
Fix: #3550  
Add getter method for `ToolCallingProperties#observations` to make spring config metadata json fully generated.
=> fix: failed to generate `spring.ai.tools.observations` config metadata

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/metadata/audio/OpenAiAudioTranscriptionResponseMetadata.java
The current situation is that calling the `toString` method of `OpenAiAudioTranscriptionResponseMetadata` will throw this exception.
=> Fix exception in `OpenAiAudioTranscriptionResponseMetadata.toString`

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatmodel.adoc
> `ChatModel.java` has been moved from `spring-ai-client-chat` to `spring-ai-model`
- Simply correct the doc link
- Reformat the code block
- Update `ChatModel` code block
=> docs: fix broken link to `ChatModel`

auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-weaviate/src/main/java/org/springframework/ai/vectorstore/weaviate/autoconfigure/WeaviateVectorStoreProperties.java
Fix order of getter and setter methods in `WeaviateVectorStoreProperties`
related pr: https://github.com/spring-projects/spring-ai/pull/3555
I apologize for the mistake.
I mistakenly placed the getContentFieldName and setContentFieldName methods between the getter and setter for objectClass. I've corrected the order to align with the conventional grouping of getter and setter methods for the same property.
```java
public String getObjectClass() {
return this.objectClass;
}
/**
* @since 1.1.0
*/
public String getContentFieldName() {
return contentFieldName;
}
/**
* @since 1.1.0
*/
public void setContentFieldName(String contentFieldName) {
this.contentFieldName = contentFieldName;
}
public void setObjectClass(String indexName) {
this.objectClass = indexName;
}
```
```java
public String …
```
=> chore: Fix order of getter and setter methods in `WeaviateVectorStoreProperties`

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
Method method = ReflectionUtils.findMethod(DateTimeTools.class, "getCurrentDateTime");
ToolCallback toolCallback = MethodToolCallback.builder()
.toolDefinition(ToolDefinition.builder() // Shouldn't method be passed here?
.description("Get the current date and time in the user's timezone")
.build())
.toolMethod(method)
.toolObject(new DateTimeTools())
.build();
=> Update tools.adoc About toolDefinition parameter transfer error

auto-configurations/models/spring-ai-autoconfigure-model-elevenlabs/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, spring-ai-docs/src/main/antora/modules/ROOT/nav.adoc
This commit updates the ElevenLabs autoconfiguration import to use the correct class name and adds a navigation link for ElevenLabs speech documentation.
=> fix(elevenlabs): correct autoconfiguration class name and add ElevenLabs speech doc link

vector-stores/spring-ai-qdrant-store/src/test/java/org/springframework/ai/vectorstore/qdrant/QdrantVectorStoreIT.java
With the changes made in https://github.com/spring-projects/spring-ai/pull/1262,
`QdrantVectorStoreIT` no longer uses `OpenAI` in its tests.
However, when creating the ApplicationContextRunner, it still requires the `OPENAI_API_KEY`.
Following that, in https://github.com/spring-projects/spring-ai/pull/1612,
a validation for the `OPENAI_API_KEY` environment variable was added to `QdrantVectorStoreIT`.
This PR removes those parts accordingly.
=> chore: Remove unnecessary environment variable validation in `QdrantVectorStoreIT`

auto-configurations/models/spring-ai-autoconfigure-model-bedrock-ai/src/main/java/org/springframework/ai/model/bedrock/converse/autoconfigure/BedrockConverseProxyChatProperties.java
Bedrock does not support topK and setting it via BedrockConverseProxyChatProperties does not have any effect.
=> Remove hardcoded topK in BedrockConverseProxyChatProperties

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
In https://docs.spring.io/spring-ai/reference/api/chatclient.html,
The `SimpleLoggerAdvisor` class documentation incorrectly shows a constructor signature:
```java
SimpleLoggerAdvisor(
Function<AdvisedRequest, String> requestToString,
Function<ChatResponse, String> responseToString
)
```
However, the actual constructor includes an additional parameter, `int order`.
Additionally, the `AdvisedRequest` class does not include a variable named `userText`.
Update the documentation to reflect the correct constructor:
```java
SimpleLoggerAdvisor(
Function<AdvisedRequest, String> requestToString,
Function<ChatResponse, String> responseToString,
int order
)
```
And Update the example to replace the incorrect `userText` reference with `request.prompt().getUserMessage()`
=> docs: correct `SimpleLoggerAdvisor` documentation

models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/MistralAiChatModel.java, models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/moderation/MistralAiModerationModel.java, models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiChatModelObservationIT.java, models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiEmbeddingModelObservationIT.java
Replaced incorrect references to 'OpenAI' with 'Mistral' in the Mistral package.
=> fix: Correct naming inconsistencies in Mistral package

auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-weaviate/src/main/java/org/springframework/ai/vectorstore/weaviate/autoconfigure/WeaviateVectorStoreAutoConfiguration.java, auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-weaviate/src/main/java/org/springframework/ai/vectorstore/weaviate/autoconfigure/WeaviateVectorStoreProperties.java, auto-configurations/vector-stores/spring-ai-autoconfigure-vector-store-weaviate/src/test/java/org/springframework/ai/vectorstore/weaviate/autoconfigure/WeaviateVectorStoreAutoConfigurationIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/weaviate.adoc, vector-stores/spring-ai-weaviate-store/src/main/java/org/springframework/ai/vectorstore/weaviate/WeaviateFilterExpressionConverter.java, vector-stores/spring-ai-weaviate-store/src/main/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStore.java, vector-stores/spring-ai-weaviate-store/src/main/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreOptions.java, vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreBuilderTests.java, vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreIT.java, vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreOptionsTests.java
related issue: https://github.com/spring-projects/spring-ai/issues/3535
Currently, the `meta field prefix` in the Weaviate vector store cannot be modified.
This PR has been improved to make it configurable, and relevant tests have been added.
- Added a new property: `spring.ai.vectorstore.weaviate.meta-field-prefix`
- Note: Whitespace is also allowed in this property.
=> Make the `meta field prefix` configurable in Weaviate vector store properties

spring-ai-vector-store/src/main/java/org/springframework/ai/vectorstore/VectorStore.java, spring-ai-vector-store/src/main/java/org/springframework/ai/vectorstore/observation/AbstractObservationVectorStore.java, vector-stores/spring-ai-azure-cosmos-db-store/src/main/java/org/springframework/ai/vectorstore/cosmosdb/CosmosDBVectorStore.java, vector-stores/spring-ai-chroma-store/src/main/java/org/springframework/ai/chroma/vectorstore/ChromaVectorStore.java, vector-stores/spring-ai-gemfire-store/src/main/java/org/springframework/ai/vectorstore/gemfire/GemFireVectorStore.java
The VectorStore#similaritySearch methods never return null. There is a data flow issue in the AbstractObservationVectorStore. However, that's only because Micrometer Observation#observe is marked as `@Nullable`, but the value returned is actually the value that the passed supplier returns, which is on control of Spring AI and is never null
=> Remove `@Nullable` from VectorStore similaritySearch

models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/ZhiPuAiEmbeddingOptions.java, models/spring-ai-zhipuai/src/test/java/org/springframework/ai/zhipuai/embedding/EmbeddingIT.java
I've run the integration tests locally, and everything checks out.
=> fix: ZhiPuAiEmbedding supports custom dimensions

models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/ZhiPuAiChatModel.java, models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/ZhiPuAiChatOptions.java, models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/api/ZhiPuAiApi.java
I couldn’t find anything about the tools1 parameter in Zhipu’s official docs. Not sure what this field is for — seems unused.
Also noticed that `buildRequestOptions` method isn’t used anywhere. ( It's a private method )
=> fix: remove unused options from ZhiPu model

spring-ai-model/src/main/java/org/springframework/ai/model/SimpleApiKey.java
After https://github.com/spring-projects/spring-ai/pull/2084, https://github.com/spring-projects/spring-ai/commit/e92616b10e36f438bfc4def8c54945ba97f931f8
`SimpleApiKey` no longer checks for empty strings.
Therefore, the corresponding message has been removed.
=> chore: fix `SimpleApiKey` assert message

spring-ai-vector-store/src/main/java/org/springframework/ai/vectorstore/observation/AbstractObservationVectorStore.java, spring-ai-vector-store/src/test/java/org/springframework/ai/vectorstore/SimpleVectorStoreTests.java, vector-stores/spring-ai-qdrant-store/src/test/java/org/springframework/ai/vectorstore/qdrant/QdrantVectorStoreIT.java
- Since the non-text documents aren't supported, we need a validation to throw exception if non text documents are encountered
- Add tests
- Add test to QdrantVectorStoreIT with the usecase provided by @devMtn30
- Add simple vector store test for the validation 
Fixes #3609
=> Validate documents for text/media check when adding to vector store

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
=> Fix typo in token configuration documentation

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
This PR improves the `getTextContent` method in `OpenAiApi` with better performance, input validation, and complete documentation.
- `Assert.notNull(content, "content cannot be null")` to prevent potential `NullPointerException`
- `.reduce("", (a, b) -> a + b)` with `.collect(Collectors.joining())` for O(n) string concatenation
- JavaDocs with parameter/return/exception descriptions for better maintainability
=> Refactor: Add null check, optimize string joining, and add JavaDocs

vector-stores/spring-ai-milvus-store/src/main/java/org/springframework/ai/vectorstore/milvus/MilvusVectorStore.java, vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/milvus/MilvusVectorStoreIT.java
In the current logic, since `createCollection` is executed without following it up with `createIndex`, the following error occurs during `describeIndex`:
```
20:36:07.664 [main] ERROR io.milvus.client.AbstractMilvusGrpcClient -- DescribeIndexRequest collectionName:test_vector_store_custom_fields, indexName: failed! Exception:{}
io.milvus.exception.ServerException: index not found[collection=test_vector_store_custom_fields]
at io.milvus.client.AbstractMilvusGrpcClient.handleResponse(AbstractMilvusGrpcClient.java:399)
at io.milvus.client.AbstractMilvusGrpcClient.describeIndex(AbstractMilvusGrpcClient.java:1423)
at io.milvus.client.MilvusServiceClient.lambda$describeIndex$32(MilvusServiceClient.java:611)
at io.milvus.client.MilvusServiceClient.retry(MilvusServiceClient.java:326)
at …
```
=> improve schema initialization logic and update deprecated code for Milvus vectorstore

.github/PULL_REQUEST_TEMPLATE.md
Update `.github/PULL_REQUEST_TEMPLATE.md`  
to replace the obsolete **CLA** bullet with a **DCO** bullet.
Spring AI now uses the Developer Certificate of Origin (DCO).  
The old CLA link was broken and misleading.
* Replaced the “Sign the CLA” bullet with:  
`Add a Signed-off-by line to each commit (\`git commit -s\`) per the DCO`
* Kept the remaining bullets (rebase, tests, build) unchanged
* Added the same DCO link used in the official blog post
No functional code changes, docs only.
Fixes #3094
=> docs: replace CLA section with DCO (#3094)

spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/ChatClient.java, spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClient.java, spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClientBuilder.java, spring-ai-client-chat/src/main/java/org/springframework/ai/chat/package-info.java
fix typos in chat client module.
thanks.
=> Fix typos in chat client module

models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/api/StreamHelper.java, models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/api/StreamHelperTests.java
- When the error event occurs, the ChatCompletionResponseBuilder is empty and hence the contentBlockReference.get() throws NPE.
- Add null check to unhandled event in addition to the logging the event type
- Add test to verify the usecase
Resolves #3740
=> Fix NPE in AnthropicApi StreamHelper

mcp/common/src/test/java/org/springframework/ai/mcp/AsyncMcpToolCallbackTest.java, mcp/common/src/test/java/org/springframework/ai/mcp/SyncMcpToolCallbackTests.java, pom.xml
For the next development version, we use MCP v0.11.0-SNAPSHOT.
Since this is a SNAPSHOT, it will be the Central Portal Snapshots repo, which you can add to your build file:
```xml
<repositories>
<repository>
<name>Central Portal Snapshots</name>
<id>central-portal-snapshots</id>
<url>https://central.sonatype.com/repository/maven-snapshots/</url>
<releases>
<enabled>false</enabled>
</releases>
<snapshots>
<enabled>true</enabled>
</snapshots>
</repository>
</repositories>
```
=> Upgrade io.modelcontextprotocol 0.10.0 -> 0.11.0-SNAPSHOT

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
* Add a Signed-off-by line to each commit (`git commit -s`) per the [DCO](https://spring.io/blog/2025/01/06/hello-dco-goodbye-cla-simplifying-contributions-to-spring#how-to-use-developer-certificate-of-origin)
[1]: https://github.com/spring-projects/spring-ai/blob/main/CONTRIBUTING.adoc
=> Fix exmaple code for "Streaming Responses"

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-helpers.adoc
- demonstrate how to filter injected MCP clients by server name
using getServerInfo().name()
This helps users dynamically choose which MCP services to expose
based on context (e.g. permissions, intent), instead of registering
all available tools unconditionally.
=> docs(mcp): add dynamic MCP client selection example

mcp/common/src/test/java/org/springframework/ai/mcp/AsyncMcpToolCallbackTest.java, mcp/common/src/test/java/org/springframework/ai/mcp/SyncMcpToolCallbackTests.java
I noticed that our CI is failing due to this commit in the MCP SDK: https://github.com/modelcontextprotocol/java-sdk/commit/87cdaf883a62077944eeae5be8ae4426cd954cf3. This PR fixes the issue. 
Relying on snapshot versions of the MCP SDK indeed seems to bring us some problems.
=> Fix: Fix CI failures

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/bedrock-converse.adoc
As mentioned in the issue, this PR completes the `Runtime Options` section in the Bedrock documentation to keep it synchronized with the latest code.
Fixes: #3842
=> GH-3842: Optimize the Bedrock documentation to keep it synchronized with the code

models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/AnthropicChatOptionsTests.java
**Add comprehensive test coverage for AnthropicChatOptions**
- Add new test methods covering edge cases and object behavior
- Test collection handling, copy behavior, and API completeness
- Enhance validation of equals/hashCode contracts and null safety
=> test: Enhance `AnthropicChatOptions` test coverage

models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiChatOptionsTests.java
The PR description above covers:
**Summary**
Added 10 new test methods to MistralAiChatOptionsTests covering edge cases, boundary conditions, and object behavior validation.
**What's Added**
- Edge cases: Empty collections, boundary values, single elements
- Object behavior: Copy isolation, equals/hashCode contracts
- API coverage: All enum values, response formats, builder chaining
- Consistency: Builder vs setter equivalence testing
**Impact**
- Improved robustness and reliability
- Better coverage of untested scenarios
=> test: Enhance `MistralAiChatOptions` test coverage with comprehensive edge cases

pom.xml
Bump postgresql JDBC driver from 42.7.5 to 42.7.7 which resolves CVE-2025-49146
=> Bump postgresql JDBC driver from 42.7.5 to 42.7.7

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
1. add a description of the responseEntity() method within the call() return values section
2. add a Note in the documentation to clarify that calling the call() method
=> Improved documentation for the `call()` method in `chatclient.adoc`

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/chroma.adoc
Spring AI is already compatible with [Chroma Cloud](https://trychroma.com). 
This PR updates the docs to explain how to configure Spring AI to use it with Chroma Cloud.
=> docs: Update ChromaDB configuration details for Chroma Cloud support

memory/repository/spring-ai-model-chat-memory-repository-jdbc/src/test/java/org/springframework/ai/chat/memory/repository/jdbc/aot/hint/JdbcChatMemoryRepositoryRuntimeHintsTest.java, spring-ai-model/src/test/java/org/springframework/ai/aot/AiRuntimeHintsTests.java, spring-ai-model/src/test/java/org/springframework/ai/aot/ToolRuntimeHintsTests.java
Adds 4 targeted test cases to strengthen runtime hints functionality across multiple components:
**ToolRuntimeHintsTests:**
- **Null ClassLoader handling** - Ensures tool hints registration doesn't fail when ClassLoader parameter is null (common in AOT processing)
**AiRuntimeHintsTests:**
- **Record validation** - Confirms records with `@JsonProperty` parameters are properly discovered for hint registration
- **Enum validation** - Verifies enums with `@JsonInclude` annotations are correctly identified for reflection hints
**JdbcChatMemoryRepositoryRuntimeHintsTest:**
- **Null ClassLoader robustness** - Validates JDBC chat memory hints registration handles null ClassLoader gracefully
These tests prevent runtime failures in native images by ensuring proper discovery of JSON-annotated …
=> test: Add comprehensive edge case and validation tests for runtime hints registration

models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/AnthropicChatModel.java, models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/client/AnthropicChatClientIT.java, models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureOpenAiChatModelIT.java, models/spring-ai-bedrock-converse/src/test/java/org/springframework/ai/bedrock/converse/BedrockConverseChatClientIT.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelObservationIT.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientIT.java, spring-ai-test/README.md
- Fix typo: 'wrapps' → 'wraps' in TODO comments across multiple files
- Fix typo: 'uitlity' → 'utility' in AnthropicChatModel comment
- Fix typo: 'occasionall' → 'occasionally' in OpenAiChatModelObservationIT comment
- Add comprehensive documentation to spring-ai-test README with usage examples
* Add a Signed-off-by line to each commit (`git commit -s`) per the [DCO](https://spring.io/blog/2025/01/06/hello-dco-goodbye-cla-simplifying-contributions-to-spring#how-to-use-developer-certificate-of-origin)
* Run a build and make sure …
=> Fix typos in comments and improve documentation

spring-ai-commons/src/test/java/org/springframework/ai/document/DocumentBuilderTests.java, spring-ai-model/src/test/java/org/springframework/ai/chat/prompt/PromptTemplateBuilderTests.java, spring-ai-vector-store/src/test/java/org/springframework/ai/vectorstore/filter/FilterExpressionBuilderTests.java
**Adds comprehensive test coverage across 3 critical Spring AI builder components:**
**PromptTemplateBuilderTests:**
- **Whitespace validation** - Ensures whitespace-only templates are rejected
- **Variable handling** - Tests empty variables, null values, missing/partial variables
- **Template rendering** - Validates complete variable substitution and empty string handling
- **Error scenarios** - Confirms proper error messages for missing template variables
**FilterExpressionBuilderTests:**
- **Operator coverage** - Tests all comparison operators
- **Complex expressions** - Validates nested groups, NOT operations, and mixed data types
- **Edge cases** - Handles null values, empty lists, special characters in keys
- **Real-world scenarios** - Tests complex filter conditions for vector …
=> test: Add comprehensive edge case and validation tests for core `Spring AI builders`

spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/ChatClient.java, spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClient.java, spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClientBuilder.java, spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/DefaultChatClientUtils.java, spring-ai-client-chat/src/test/java/org/springframework/ai/chat/client/ChatClientTest.java, spring-ai-client-chat/src/test/java/org/springframework/ai/chat/client/DefaultChatClientTests.java
- Add `metadata` methods to `PromptUserSpec` and `PromptSystemSpec` interfaces
- Update `DefaultChatClientRequestSpec` to handle user and system `metadata`
- Modify `DefaultChatClientUtils` to include `metadata` in `SystemMessage` and `UserMessage` builders
- Add comprehensive test coverage for `metadata` functionality
--- 
This PR allows users to set the `metadata` field for `UserMessage` and `SystemMessage` through `Consumer<PromptUserSpec>` and `Consumer<PromptSystemSpec>`.
Users can set information like message ID through `metadata`, and then get them in `ChatMemoryRepository`.  
Example as follows:
```java
private static final ChatMemoryRepository myChatMemoryRepository = new ChatMemoryRepository() {
@Override
public void saveAll(String conversationId, List<Message> messages) { …
```
=> feat: Add `metadata` support to `PromptUserSpec` and `PromptSystemSpec` in ChatClient

models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureEmbeddingsOptionsTests.java, models/spring-ai-oci-genai/src/test/java/org/springframework/ai/oci/cohere/OCICohereChatOptionsTests.java, vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/weaviate/WeaviateVectorStoreOptionsTests.java
**Added extensive test coverage for configuration options classes:**
**OCICohereChatOptions:**
- Builder pattern validation (minimal fields, null handling)
- Deep copy verification and immutability testing
- Boundary value testing (min/max values for temperature, topP, etc.)
- Collection handling (empty lists, null setters)
- State transition testing
**AzureEmbeddingsOptions:**
- Multiple input handling and order preservation
- Options override behavior
- Different metadata modes
- Concurrent request isolation
- Empty input edge cases
**WeaviateVectorStoreOptions:**
- Input validation with proper error messages
- Special character and whitespace handling
- State preservation during partial failures
- Case sensitivity verification
- Default value behavior
These tests improve robustness by …
=> test: Add comprehensive test coverage for `OCICohereChatOptions`, `AzureEmbeddingsOptions`, `WeaviateVectorStoreOptions` classes

models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/AzureChatCompletionsOptionsTests.java, models/spring-ai-postgresml/src/test/java/org/springframework/ai/postgresml/PostgresMlEmbeddingOptionsTests.java
**Adds thorough test coverage for PostgresMlEmbeddingOptions and AzureOpenAiChatOptions which include:**
`PostgresMlEmbeddingOptions `
- Empty and complex kwargs handling
- All vector types and metadata modes validation
- Option merging with null inputs and preservation of original options
- Builder pattern chaining behavior
- Edge cases for complex nested kwargs structures
`AzureOpenAiChatOptions `
- Minimal configuration options validation
- Empty collections handling (stop lists, logit bias)
- Disabled logprobs configuration
- Single stop sequence processing
- Builder pattern validation
- Parameterized testing for response format types
These tests ensure robust validation of embedding configuration options and proper handling of various input scenarios.
Improves reliability by testing …
=> test: Add comprehensive test coverage for `AzureOpenAiChatOptions` and `PostgresMlEmbeddingOptions`

spring-ai-client-chat/src/main/java/org/springframework/ai/chat/evaluation/FactCheckingEvaluator.java, spring-ai-client-chat/src/main/java/org/springframework/ai/chat/evaluation/RelevancyEvaluator.java
Keep the same pass check behavior for `FactCheckingEvaluator` and `RelevancyEvaluator`, and avoid NPE.
Some test cases:
- When `evaluationResponse` is `null`, return false.
- When `evaluationResponse` is `yes`, return true.
- When `evaluationResponse` is `Yes`, return true.
- When `evaluationResponse` is `yES`, return true.
- When `evaluationResponse` is `no and yes`, return false.
- When `evaluationResponse` is `yes. `, return false.
=> Keep the same pass check behavior for Evaluator

.github/workflows/continuous-inspection.yml, .github/workflows/continuous-integration.yml, .github/workflows/documentation-upload.yml, .github/workflows/pr-check.yml
I noticed that some of the GitHub actions are using `mvn` and not `./mvnw` the Maven Wrapper part of the project. Additionally I noticed that some commands are not using `--batch-mode`. This leads to builds which have:
```
Downloaded from central-portal-snapshots: https://central.sonatype.com/repository/maven-snapshots/io/modelcontextprotocol/sdk/mcp-bom/0.11.0-SNAPSHOT/mcp-bom-0.11.0-20250716.113131-38.pom (2.1 kB at 8.4 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Progress (1): 4.1/169 kB
Progress (1): 8.2/169 kB
Progress (1): 12/169 kB 
Progress (1): 16/169 kB
Progress (1): 20/169 kB
````
The default "CI/CD build" already contains `--batch-mode`. However, some other ones such as the "Documentation Upload" …
=> Use maven wrapper and batch-mode in GitHub Actions

.github/workflows/continuous-integration.yml
The CI was failing because the 'Generate assembly' step was trying to run ./mvnw from within the spring-ai-docs directory, but the Maven wrapper script only exists in the repository root.
Fixed by changing './mvnw' to '../mvnw' to reference the script from the parent directory while maintaining the correct working directory for the assembly generation.
=> Fix CI workflow: Use ../mvnw for assembly generation in spring-ai-docs

spring-ai-model/src/main/java/org/springframework/ai/embedding/observation/DefaultEmbeddingModelObservationConvention.java
We can use `Optional` to check null, otherwise we will have too many null check. And avoid NPE.
In the code design, we have too many nested levels, `Optional` is a good choice.
=> Polish: Use `Optional` to check null, and avoid NPE.

spring-ai-retry/src/main/java/org/springframework/ai/retry/RetryUtils.java
#4082  
Network connectivity errors like "HTTP/1.1 header parser received no bytes" were not being retried across all Spring AI model providers. These
ResourceAccessException errors occurred during poor network conditions but failed immediately instead of utilizing the existing retry mechanism.        
Solution
Added ResourceAccessException.class to both DEFAULT_RETRY_TEMPLATE and SHORT_RETRY_TEMPLATE in RetryUtils.java. This enables automatic retry of
network-level connectivity issues with the same exponential backoff strategy used for other transient errors.
Impact
- ✅ Fixes network connectivity issues for all 19+ AI model providers (OpenAI, DeepSeek, Anthropic, etc.)
- ✅ Maintains existing retry behavior for TransientAiException
- ✅ Uses established retry configuration (10 attempts, …
=> Issue 4082  Fix ResourceAccessException retry for network connectivity errors

models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/client/OpenAiChatClientIT.java
Fix OpenAiChatClientIT.beanStreamOutputConverterRecords test that was failing intermittently when run as part of a test suite due to empty streaming chunks causing malformed JSON during aggregation.
Changes:
- Filter out empty/null text chunks before aggregation to prevent malformed JSON
- Replace silent return with explicit test failure when streaming aggregation produces empty results
- Add debugging logs to aid troubleshooting of streaming response issues
The test now properly detects and reports streaming aggregation problems instead of silently skipping, improving CI reliability and error detection.
Auto-cherry-pick to 1.0.x
Fixes #4134
Signed-off-by: Mark Pollack <mark.pollack@broadcom.com>
=> Fix intermittent streaming response aggregation test failure

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatOptions.java, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/api/OpenAiApiIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
Add gpt-5 models and update their tests
=> Feat: add gpt 5 models and verbosity param

models/spring-ai-google-genai/src/main/java/org/springframework/ai/google/genai/GoogleGenAiChatModel.java
This will return the actual modelVersion used on a chat response, e.g. request goes to gemini-2.0-pro, response returns gemini-2.0-pro-002.
=> chore(google genai): return the actual model version used for chat

pom.xml
Update io.swagger.core.v3:swagger-annotations to 2.2.30
Fixes https://github.com/spring-projects/spring-ai/issues/4185 where a method used is only available in a newer version.
=> Bump io.swagger.core.v3:swagger-annotations from 2.2.25 to 2.2.30

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/advisors.adoc
correct typo from 'are' to 'and' in advisors.adoc
=> docs: Update advisors.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/docker-compose.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/testcontainers.adoc
As discussed in https://github.com/spring-projects/spring-ai/pull/4241, the current documentation doesn't explain that any service connection from spring boot can be used in spring ai. Updating the documentation to link to the matching spring boot documentation.
=> Update docker services documentation

models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiChatModel.java
Reordering might occur due to `Flux::flatMap` not having ordering guarantees, `flatMapSequential` fixes this.
See #4155 
I did not update any tests because the reproduction relies on a race condition and it was pretty hard for me to reproduce it locally.
<details>
<summary>Default PR description</summary>
* Add a Signed-off-by line to each commit (`git commit -s`) per the [DCO](https://spring.io/blog/2025/01/06/hello-dco-goodbye-cla-simplifying-contributions-to-spring#how-to-use-developer-certificate-of-origin)
* Run a build and …
=> Fix reordering issue in AzureOpenAiChatModel (Fixes #4155)

spring-ai-template-st/src/main/java/org/springframework/ai/template/st/StTemplateRenderer.java
This PR removes unnecessary null checks from the StTemplateRenderer class to simplify the code and avoid redundant validation.
- Removed redundant null checks on template variables map keys in the apply method.
- Simplified validation logic by eliminating defensive checks that are unlikely to occur.
=> chore: remove unnecessary null checks

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
correct typo from 'tools' to 'toolNames' in tools.adoc
=> docs: Update tools.adoc

memory/repository/spring-ai-model-chat-memory-repository-jdbc/src/main/java/org/springframework/ai/chat/memory/repository/jdbc/JdbcChatMemoryRepository.java
The inner method JdbcChatMemoryRepositoryDialect#from already contains exception handling logic. The outer try-catch block is unnecessary and can be safely removed to avoid redundant exception handling and improve code clarity.
=> remove redundant try-catch in JdbcChatMemoryRepository

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/zhipuai-chat.adoc
- Change default model from 'GLM-3-Turbo' to 'glm-4-air' in doc
- Fix formatting consistency in documentation
The current default model is glm-4-air: 
https://github.com/spring-projects/spring-ai/blob/c7b7d691e409ebdbbd4407451fbcbc6125ee5a8a/models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/api/ZhiPuAiApi.java#L74
=> docs(zhipu): fix zhipuai-chat.adoc

spring-ai-client-chat/src/main/java/org/springframework/ai/chat/client/ChatClient.java
Improve method param name in `ChatClient.Builder.defaultAdvisors(Advisor...)` from `advisor` to `advisors`.
Method parameter naming rules should be consistent.
```java
interface AdvisorSpec {
AdvisorSpec advisors(Advisor... advisors);
}
```
```java
interface ChatClientRequestSpec {
ChatClientRequestSpec advisors(Advisor... advisors);
}
```
=> Improve method param name in ChatClient.Builder.defaultAdvisors()

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/oci-genai/cohere-chat.adoc
The OCI Cohere Chat documentation currently lists the property prefix as `spring.ai.oci.genai.chat.cohere`. However, the `OCICohereChatModelProperties`
class expects `spring.ai.oci.genai.cohere.chat` instead.
This PR corrects the documentation so that the prefix matches the code.
References:
- Documentation showing incorrect prefix: [https://docs.spring.io/spring-ai/reference/api/chat/oci-genai/cohere-chat.html](https://docs.spring.io/spring-ai/reference/api/chat/oci-genai/cohere-chat.html)
- Javadoc showing correct prefix: [https://github.com/spring-projects/spring-ai/blob/main/auto-configurations/models/spring-ai-autoconfigure-model-oci-genai/src/main/java/org/springframework/ai/model/oci/genai/autoconfigure/OCICohereChatModelProperties.java#L31](https://github.com/spring-projects/spring …
=> [Fixes #4436] Fix Typo in the OCI GenAI Cohere Chat Documentation

spring-ai-model/src/main/java/org/springframework/ai/util/json/schema/JsonSchemaGenerator.java, spring-ai-model/src/test/java/org/springframework/ai/util/json/JsonSchemaGeneratorTests.java
- For method input parameters, if the JSON schema generator adds OpenAPI "format" property, some LLMs (ex: Mistral) fail to process the request. Hence, removing this specific property from the JSON schema
- This issue was uncovered by MistralAiChatModelIT#chatMemoryWithTools where the method toolcallback is used
Auto-cherry-pick to 1.0.x
Fixes #4524
=> Fix JsonSchemaGenerator for method input parameters

models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/api/ZhiPuAiApi.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/zhipuai-chat.adoc
- Include Z.ai international site link for non-Chinese speakers
- Add `glm-4.6` to the list of supported chat models
Effect of the document changes:
=> docs: Add Z.ai international site and glm-4.6 support
