antora-playbook.yml
[1]: https://github.com/spring-projects/spring-batch/blob/main/CONTRIBUTING.md
=> Update to antora-ui-spring 0.3.5

spring-ai-docs/pom.xml, spring-ai-docs/src/main/antora/antora-playbook.yml
[1]: https://github.com/spring-projects/spring-batch/blob/main/CONTRIBUTING.md
=> Add asciidoctor-mathjax

spring-ai-core/src/main/resources/embedding/embedding-model-dimensions.properties
=> Fix typo in embedding-model-dimensions.properties

vector-stores/spring-ai-neo4j-store/README.md
Heavily "inspired" by the PgVectorStore readme but I think it's useful to have the same structure and examples for maintenance.
=> Add readme for Neo4jVectorStore

spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/ollama/OllamaAutoConfigurationIT.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/chroma/ChromaVectorStoreAutoConfigurationIT.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/pgvector/PgVectorStoreAutoConfigurationIT.java, vector-stores/spring-ai-chroma/src/test/java/org/springframework/experimental/ai/chroma/ChromaApiIT.java, vector-stores/spring-ai-chroma/src/test/java/org/springframework/experimental/ai/vectorstore/BasicAuthChromaWhereIT.java, vector-stores/spring-ai-chroma/src/test/java/org/springframework/experimental/ai/vectorstore/ChromaVectorStoreIT.java, vector-stores/spring-ai-chroma/src/test/java/org/springframework/experimental/ai/vectorstore/TokenSecuredChromaWhereIT.java, vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/MilvusVectorStoreIT.java, vector-stores/spring-ai-pgvector-store/src/test/java/org/springframework/ai/vectorstore/PgVectorStoreIT.java
* Specify tag images
* Use getHost() instead of hardcoded `localhost`
=> Cleanup tests using testcontainers

spring-ai-core/src/main/java/org/springframework/ai/prompt/Prompt.java, spring-ai-core/src/main/java/org/springframework/ai/vectorstore/SearchRequest.java
I used the suggested implementations from IntelliJ, which seemed to be good. Let me know if there is some other implementation you'd prefer to see.
=> Add equals() and hashCode() for Prompt and SearchRequest

spring-ai-docs/src/main/antora/modules/ROOT/pages/concepts.adoc
I corrected the link to Arxiv.
=> Fix link pointing to arxiv

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/milvus/MilvusVectorStoreAutoConfiguration.java
Fix the wrong copying of configuration params
=> fix: milvus builder configuration params setters

spring-ai-spring-boot-starters/spring-ai-starter-azure-openai/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-azure-store/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-chroma-store/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-milvus-store/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-ollama/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-openai/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-pgvector-store/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-pinecone-store/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-transformers-embedding/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-vertex-ai/pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-weaviate-store/pom.xml
starters do not provide spring-boot-starter-test
=> Cleanup starters

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/prompt.adoc
Fix bullet point formatting for Function Role on the Prompts page.
=> Fix Prompts documentation typos

README.md
This pull request removes merge chevrons from the README.md and fixes the README.md to what was intended.   No code this pull request.
=> Issue 196 Merge Chevrons in README md

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/clients/azure-openai.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/onnx.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/etl-pipeline.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/output-parser.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/prompt.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/azure.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/concepts.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/getting-started.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/index.adoc
Documentation fixes.
Resolved code formatting issues, fixed minor typos, general small edits for clarity.
=> Documentation fixes, clean and polish

spring-ai-docs/src/main/antora/modules/ROOT/pages/concepts.adoc
models introduction: add Google Gemini models
=> Update concepts.adoc: add Google Gemini

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/ollama/OllamaChatProperties.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/ollama/OllamaEmbeddingProperties.java
=> Include metadata for nested config props in Ollama

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/clients/azure-openai.adoc
Closes https://github.com/spring-projects/spring-ai/issues/236
=> Fix typo in Azure OpenAI documentation

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/chroma.adoc
=> updated sample code in chroma documentation

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/azure.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/neo4j.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/pgvector.adoc
Fixed several documentation bugs across the following vector DBs:
- Postgres/PGvector
- Neo4j
- Azure AI Search
Added required properties/code samples to successfully implement Neo4j as a VectorStore. These were missing.
Other docs fixes as appropriate.
=> Updated several vector db docs to fix errors and to expand on instructions for successful outcomes

pom.xml, spring-ai-bom/pom.xml, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/getting-started.adoc
=> Add spring AI Bom and related docs

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/openai-embeddings.adoc
Fixed small error in OpenAiChatOptions implementation documentation
=> Update openai-embeddings.adoc to fixe error in OpenAiChatOptions implementation documentation

spring-ai-core/src/main/java/org/springframework/ai/chat/messages/FunctionMessage.java
Change the MessageType to FUNCTION in FunctionMessage
=> Use MessageType.FUNCTION for FunctionMessage

vector-stores/spring-ai-redis/src/main/java/org/springframework/ai/vectorstore/RedisVectorStore.java
Fixes https://github.com/spring-projects/spring-ai/issues/422 using try-with-resources.
=> Fix RedisVectorStore not closing Jedis pipelines

spring-ai-test/README.md
=> Fixed syntax in reference

README.md
=> Fixed typo in 'reference'

spring-ai-core/src/main/java/org/springframework/ai/image/ImageMessage.java
spring-ai > spring-ai-core > src > main > java > org > springframework > image > ImageMessage 
line 45 : 
return "mageMessage{" + "text='" + text + '\'' + ", weight=" + weight + '}';
>>
return "ImageMessage{" + "text='" + text + '\'' + ", weight=" + weight + '}';
=> modified ImageMessage.java line 45: mage > Image

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
=> fix: fix comment style error

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
=> Remove invalid code

models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/api/MistralAiApi.java, models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/api/MistralAiStreamFunctionCallingHelper.java, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
- Refactor MIstralAiStreamFunctionCallingHelper to MistralAiStreamFunctionCallingHelper
- Replace none to auto in OpenAi ToolChoiceBuilder 'AUTO'
=> Refactor MistralAi class and Fix OpenAi ToolChoiceBuilder value

pom.xml, spring-ai-bom/pom.xml, spring-ai-spring-boot-autoconfigure/pom.xml, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/elasticsearch/ElasticsearchVectorStoreAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/elasticsearch/ElasticsearchVectorStoreProperties.java, spring-ai-spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/elasticsearch/ElasticsearchVectorStoreAutoConfigurationIT.java, spring-ai-spring-boot-starters/spring-ai-starter-elasticsearch-store/pom.xml
* Add spring-ai-elasticsearch-store-spring-boot-starter
* Register spring-ai-elasticsearch-store-spring-boot-starter in bom
Fixes #475
=> Add Elasticsearch vector store auto-configuration

spring-ai-core/src/main/java/org/springframework/ai/chat/prompt/PromptTemplate.java, spring-ai-core/src/main/java/org/springframework/ai/chat/prompt/PromptTemplateMessageActions.java
This would allow using the PromptTemplate for multimodal usecases.
=> Extend the PromptTemplate to support Message media content

models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/titan/api/TitanChatBedrockApi.java
fix Access modifier
close #490
=> Fix TitanChatBedrockApi.java

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/openai-chat.adoc
=> broken links in OpenAI docs

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/ollama-chat.adoc
=> Fixed typo in ollama-chat.adoc

models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/anthropic3/api/Anthropic3ChatBedrockApi.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/bedrock/bedrock-anthropic3.adoc
Add support for AWS bedrock claude3 opus model support
=> Add support for AWS bedrock claude3 opus model support

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/elasticsearch.adoc
=> Add documentation for Elasticsearch VectorStore.

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/etl-pipeline.adoc
=> fix wrong document code examples

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/cassandra/CassandraVectorStoreAutoConfiguration.java
@tzolov discovered this slip-up (from me) while working on a use case
=> Fix CassandraVectorStoreAutoConfiguration's @ConditionalOnClass to not include EmbeddingClient

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/functions/openai-chat-functions.adoc
=> Implement a function, not functions

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/openai-embeddings.adoc
This PR fixes the sample in the "Manual Configuration" section of OpenAI Embeddings API.
=> Fix sample in "Manual Configuration" section of OpenAI Embeddings API

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiImageOptions.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/openai/OpenAiImageProperties.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/openai/OpenAiAutoConfigurationIT.java
=> OpenAI: Fix model property being overwritten by default value

models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/titan/api/TitanChatBedrockApi.java, models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/titan/BedrockTitanChatClientIT.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/bedrock/bedrock-titan.adoc
Release note: https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-titan-text-premier-amazon-bedrock/
=> Add AWS Bedrock Amazon Titan Text Premier model support.

spring-ai-docs/src/main/antora/modules/ROOT/pages/concepts.adoc
This PR updates the documentation related to function invocation on the Spring AI / AI Concepts project page.
Enhancing overall readability and accuracy of the documentation.
These updates aim to make it easier for users to understand and implement function invocation in their projects.
=> Update concepts.adoc documentation for clarity and accuracy

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
=> Fix typo chatclient.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/onnx.adoc
=> docs(onnx): add additional info for configuration properties and note for ONNX transformer.

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
=> Fix typo: Change 'context' to 'content'

pom.xml
This will help fix issue reported by me in #836 .
Hi @tzolov , can you help take a look at this? Thanks very much.
=> Upgrade djl to 0.28.0 

spring-ai-spring-boot-autoconfigure/pom.xml, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/oracle/OracleVectorStoreAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/oracle/OracleVectorStoreProperties.java, spring-ai-spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/oracle/OracleVectorStoreAutoConfigurationIT.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/oracle/OracleVectorStorePropertiesTests.java, spring-ai-spring-boot-autoconfigure/src/test/resources/oracle/initialize.sql, spring-ai-spring-boot-starters/spring-ai-starter-oracle-store/pom.xml, vector-stores/spring-ai-oracle-store/src/main/java/org/springframework/ai/vectorstore/OracleVectorStore.java, vector-stores/spring-ai-oracle-store/src/test/java/org/springframework/ai/vectorstore/OracleVectorStoreIT.java
- force override the outdated SpringBoot Oracle version.
- add auto-config tests.
=> Fix Oracle Vector Store dependencies

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/etl-pipeline.adoc
- Fixed missing variable assignment in ParagraphPdfDocumentReader code snippet
=> ETL-Pipeline ParagraphPdfDocumentReader Snippet fix

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
=> Update documentation for OpenAiApi.ChatCompletionRequest's constructor

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/docker-compose.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/testcontainers.adoc, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/typesense/TypesenseConnectionDetails.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/typesense/TypesenseServiceClientProperties.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/typesense/TypesenseVectorStoreAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/typesense/TypesenseVectorStoreAutoConfigurationIT.java, spring-ai-spring-boot-docker-compose/src/main/java/org/springframework/ai/docker/compose/service/connection/typesense/TypesenseDockerComposeConnectionDetailsFactory.java, spring-ai-spring-boot-docker-compose/src/main/java/org/springframework/ai/docker/compose/service/connection/typesense/TypesenseEnvironment.java, spring-ai-spring-boot-docker-compose/src/main/resources/META-INF/spring.factories, spring-ai-spring-boot-docker-compose/src/test/java/org/springframework/ai/docker/compose/service/connection/typesense/TypesenseDockerComposeConnectionDetailsFactoryTests.java, spring-ai-spring-boot-docker-compose/src/test/java/org/springframework/ai/docker/compose/service/connection/typesense/TypesenseEnvironmentTests.java, spring-ai-spring-boot-docker-compose/src/test/resources/org/springframework/ai/docker/compose/service/connection/typesense/typesense-compose.yaml, spring-ai-spring-boot-testcontainers/pom.xml, spring-ai-spring-boot-testcontainers/src/main/java/org/springframework/ai/testcontainers/service/connection/typesense/TypesenseContainerConnectionDetailsFactory.java, spring-ai-spring-boot-testcontainers/src/main/resources/META-INF/spring.factories, spring-ai-spring-boot-testcontainers/src/test/java/org/springframework/ai/testcontainers/service/connection/typesense/TypesenseContainerConnectionDetailsFactoryTest.java, vector-stores/spring-ai-typesense-store/src/test/java/org/springframework/ai/vectorstore/TypesenseVectorStoreIT.java
Docker Compose and Testcontainers Service Connection support for Typesense.
Also, polish tests.
=> Add support for Typesense Service Connection

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/chroma/ChromaVectorStoreAutoConfiguration.java, spring-ai-spring-boot-docker-compose/src/main/java/org/springframework/ai/docker/compose/service/connection/chroma/ChromaDockerComposeConnectionDetailsFactory.java, spring-ai-spring-boot-docker-compose/src/main/java/org/springframework/ai/docker/compose/service/connection/chroma/ChromaEnvironment.java, spring-ai-spring-boot-docker-compose/src/test/java/org/springframework/ai/docker/compose/service/connection/chroma/ChromaEnvironmentTests.java, spring-ai-spring-boot-docker-compose/src/test/java/org/springframework/ai/docker/compose/service/connection/chroma/ChromaWithTokenDockerComposeConnectionDetailsFactoryTests.java, spring-ai-spring-boot-docker-compose/src/test/resources/org/springframework/ai/docker/compose/service/connection/chroma/chroma-with-token-compose.yaml, spring-ai-spring-boot-testcontainers/src/main/java/org/springframework/ai/testcontainers/service/connection/chroma/ChromaContainerConnectionDetailsFactory.java, spring-ai-spring-boot-testcontainers/src/test/java/org/springframework/ai/testcontainers/service/connection/chroma/ChromaWithTokenContainerConnectionDetailsFactoryTest.java, vector-stores/spring-ai-chroma-store/src/test/java/org/springframework/ai/chroma/ChromaApiIT.java, vector-stores/spring-ai-chroma-store/src/test/java/org/springframework/ai/vectorstore/BasicAuthChromaWhereIT.java, vector-stores/spring-ai-chroma-store/src/test/java/org/springframework/ai/vectorstore/TokenSecuredChromaWhereIT.java
Read `CHROMA_SERVER_AUTHN_CREDENTIALS` env var from compose file and Testcontainers definition to configure the connection details for ChromaDB.
Also, update chromadb images to 0.5.0 and fix test with token and basic authentication. See https://docs.trychroma.com/deployment/auth
=> Support ChromaDB's CHROMA_SERVER_AUTHN_CREDENTIALS env var in Docker Compose and Testcontainers

spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/qdrant/QdrantVectorStoreAutoConfigurationIT.java, vector-stores/spring-ai-qdrant-store/src/test/java/org/springframework/ai/vectorstore/qdrant/QdrantVectorStoreIT.java
Use helper methods provided by Testcontainers.
=> Polish Qdrant tests

spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/QuestionAnswerAdvisor.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/QuestionAnswerAdvisorTests.java
=> Fix FILTER_EXPRESSION typo

models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/client/AnthropicChatClientIT.java, models/spring-ai-anthropic/src/test/resources/application-logging-test.properties, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatModel.java, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatOptions.java, models/spring-ai-openai/src/test/resources/application-logging-test.properties, spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/SimpleLoggerAdvisor.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/SimpleLoggerAdvisorTests.java, spring-ai-core/src/test/resources/application-logging-test.properties, spring-ai-core/src/test/resources/logback.xml, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
=> Add customizable logger advisor

spring-ai-docs/src/main/antora/modules/ROOT/pages/index.adoc
Opening a new PR as requested by @tzolov in https://github.com/spring-projects/spring-ai/pull/784.
Thanks!
=> Update index.adoc to include MongoDB Atlas

vector-stores/spring-ai-mongodb-atlas-store/src/main/java/org/springframework/ai/vectorstore/MongoDBAtlasFilterExpressionConverter.java
Corrected the misspelling of 'MongoDB' in the javadoc
=> Minor javadoc improvements

spring-ai-core/src/main/java/org/springframework/ai/document/Document.java, vector-stores/spring-ai-mongodb-atlas-store/src/main/java/org/springframework/ai/vectorstore/MongoDBAtlasFilterExpressionConverter.java
More exhaustive error message when creating a Document.
=> :fix: constructor error messages

spring-ai-docs/src/main/antora/modules/ROOT/pages/concepts.adoc
Add line break at [Function Calling] chapter
=> Add line break at [Function Calling] chapter

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chatclient.adoc
This change resolves issue issue #966 by correcting the typo mistake.
signed-off-by : Ashwin Krishna K [ashwinkrishna7151@gmail.com]
=> Update typo mistake in chatclient.adoc

spring-ai-core/src/main/java/org/springframework/ai/chat/messages/MessageType.java
- Add comment in MessageType for readability
resolved #972
=> Add comment in MessageType for readability

models/spring-ai-mistral-ai/src/test/java/org/springframework/ai/mistralai/MistralAiEmbeddingIT.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/embedding/EmbeddingIT.java
Fix integration tests for OpenAI and Mistral AI
=> Update tests for EmbeddingResponseMetadata

models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/AnthropicTestConfiguration.java
=> fix: test name error

models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/api/AnthropicApi.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/anthropic/AnthropicAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/anthropic/AnthropicConnectionProperties.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/anthropic/AnthropicAutoConfigurationIT.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/anthropic/AnthropicPropertiesTests.java
- add new spring.ai.anthropic.beta-version property.
- add ITs.
Resolves #1068
=> Anthropic:  make the beta features header value configurable

models/spring-ai-qianfan/src/main/java/org/springframework/ai/qianfan/QianFanChatModel.java, models/spring-ai-qianfan/src/test/java/org/springframework/ai/qianfan/chat/QianFanChatModelIT.java
fix `QianFan` chat model error on role based message call and add role based unit tests
related issue https://github.com/spring-projects/spring-ai/issues/1017
=> fix: QianFan role based chat model & unit tests

models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/AnthropicChatModel.java, models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/api/AnthropicApi.java, models/spring-ai-anthropic/src/main/java/org/springframework/ai/anthropic/api/StreamHelper.java, models/spring-ai-anthropic/src/test/java/org/springframework/ai/anthropic/api/tool/AnthropicApiToolIT.java, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatModel.java, spring-ai-core/src/main/java/org/springframework/ai/chat/messages/AssistantMessage.java, spring-ai-core/src/main/java/org/springframework/ai/chat/metadata/ChatGenerationMetadata.java, spring-ai-core/src/main/java/org/springframework/ai/chat/model/AbstractToolCallSupport.java
- factor out the common funciton calling logic form AnthropicChatModel to the AbstractToolCallSupport.
- improve the AbstractToolCallSupport isToolCall to handle OpenAi and Anthropic.
- fix an issue with the function calling streaming aggreagation leading to lost usage statistics.
- small code improvements for OpenAiChatModel.
=> Improve Anthropic function calling

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/functions.adoc
- modify streeming to streaming
=> Docs: Edit typo

models/spring-ai-vertex-ai-gemini/src/main/java/org/springframework/ai/vertexai/gemini/VertexAiGeminiChatModel.java, spring-ai-core/src/main/java/org/springframework/ai/model/function/AbstractFunctionCallSupport.java
Align with AbstractToolCallSupport
=> Streamline the VertexAI Gemini Function Calling

pom.xml
Updated version resolves CVE-2024-22271
=> Bump spring-cloud-function-context from 4.1.1 to 4.1.3

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/chat/observation/ChatObservationAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/embedding/observation/EmbeddingObservationAutoConfiguration.java
=> Fix autoconfig dependency when metrics enabled

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/metadata/OpenAiUsage.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/metadata/OpenAiUsageTests.java
=> Fix NPE in OpenAiUsage

pom.xml, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/vectorstore/weaviate/WeaviateVectorStoreAutoConfigurationIT.java, spring-ai-spring-boot-testcontainers/src/test/java/org/springframework/ai/testcontainers/service/connection/weaviate/WeaviateContainerConnectionDetailsFactoryTest.java, vector-stores/spring-ai-weaviate-store/src/test/java/org/springframework/ai/vectorstore/WeaviateVectorStoreIT.java
Weaviate module contains the wait strategy.
=> Update testcontainers version to 1.20.1

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/pinecone.adoc
fix  `vectorStore.add(List.of(document));` to `vectorStore.add(documents);`
=> Docs: fix pinecone example

vector-stores/spring-ai-pinecone-store/src/main/java/org/springframework/ai/vectorstore/PineconeVectorStoreHints.java, vector-stores/spring-ai-pinecone-store/src/main/resources/META-INF/spring/aot.factories
=> pincecone vector aot hints

spring-ai-bom/pom.xml
=> Add spring-ai-spring-boot-docker-compose to BOM

spring-ai-core/src/main/java/org/springframework/ai/embedding/TokenCountBatchingStrategy.java
Fixes #1341 by creating new lists to submit to `batches`.
=> Fixing bug in TokenCountBatchingStrategy

vector-stores/spring-ai-elasticsearch-store/src/main/java/org/springframework/ai/vectorstore/ElasticsearchVectorStore.java
Adding version and actually adding the header to the client
=> Fixing Elasticsearch's user agent header

spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/chat/observation/ChatObservationAutoConfiguration.java
When Micrometer Tracing is not in the classpath, Spring AI makes Spring Boot fail the startup.
=> Fix chat model autoconfig when no Micrometer Tracing in context

spring-ai-docs/src/main/antora/modules/ROOT/pages/observabilty/index.adoc
* Update attributes
* Add more information on optional attributes and risks
* Include documentation for events.
=> Update Observability documentation

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/embeddings/bedrock-cohere-embedding.adoc
This fixes a small typo in the documentation.
=> Update bedrock-cohere-embedding.adoc to fix an incorrect description

models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/ZhiPuAiChatModel.java
related issue https://github.com/spring-projects/spring-ai/issues/1502
=> remove useless TODO comment on ZhiPu chat model

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/azure.adoc
=> Update azure.adoc fixing type

spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/SimpleLoggerAdvisor.java, spring-ai-core/src/test/java/org/springframework/ai/chat/client/advisor/SimpleLoggerAdvisorTests.java
- Order value modification added
- Added Test to validate order acceptance
=> Add the ability to customize SimpleLoggerAdvisor order

pom.xml, spring-ai-bom/pom.xml, vector-stores/spring-ai-azure-cosmos-db-store/pom.xml
Defined the version for Azure Cosmos DB
Added dependencies for the azure-cosmos-db-store module and boot starter
referred to this link for the version
https://mvnrepository.com/artifact/com.azure/azure-spring-data-cosmos
=> Add azure-cosmos-db to pom.xml

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/testing.adoc
I modified the code so that the test code would pass through.
=> modify a document

spring-ai-core/src/main/java/org/springframework/ai/chat/messages/MessageType.java, spring-ai-core/src/main/java/org/springframework/ai/chat/prompt/ChatOptions.java, spring-ai-core/src/main/java/org/springframework/ai/evaluation/FactCheckingEvaluator.java, spring-ai-core/src/main/java/org/springframework/ai/model/function/FunctionCallingOptions.java, spring-ai-core/src/main/java/org/springframework/ai/observation/conventions/AiObservationMetricNames.java, spring-ai-core/src/main/java/org/springframework/ai/vectorstore/observation/VectorStoreObservationContext.java, spring-ai-docs/src/main/antora/modules/ROOT/pages/getting-started.adoc
=> Fix grammar and minor typos in documentation as well as Javadoc

vector-stores/spring-ai-pinecone-store/src/main/java/org/springframework/ai/vectorstore/PineconeVectorStore.java
remove duplicated config with ApiKey line 324, 327
=> remove duplicated config building with ApiKey

.github/workflows/pr-check.yml
It only executes unit tests.
Checkstyle and Spring Java Format are executed.
=> Enable tests on PRs

models/spring-ai-openai/src/test/java/org/springframework/ai/openai/acme/AcmeIT.java, models/spring-ai-openai/src/test/java/org/springframework/ai/openai/vectorstore/SimplePersistentVectorStoreIT.java, spring-ai-core/src/test/java/org/springframework/ai/vectorstore/SimpleVectorStoreTests.java, spring-ai-integration-tests/src/test/java/org/springframework/ai/integration/tests/TestApplication.java
- Use SimpleVectorStoreBuilder for SimpleVectorStore instance creation
=> Fix SimpleVectorStore' deprecated constructor use

spring-ai-core/src/main/java/org/springframework/ai/vectorstore/SimpleVectorStore.java
My first commit to test how it works here
=> Simplified method (deleted unnecessary local variable)

models/spring-ai-minimax/src/main/java/org/springframework/ai/minimax/api/MiniMaxApi.java
I referred to this page
https://www.minimaxi.com/en/news/abab7-preview-release
=> Add New Version of Minimax ChatModel

spring-ai-core/src/main/java/org/springframework/ai/document/Document.java, vector-stores/spring-ai-pgvector-store/src/main/java/org/springframework/ai/vectorstore/pgvector/PgVectorStore.java, vector-stores/spring-ai-pgvector-store/src/test/java/org/springframework/ai/vectorstore/pgvector/PgVectorStoreIT.java
Reverts spring-projects/spring-ai#2014
=> Revert "Remove UUID Enforcement for ID Column in PGVectorStore"

vector-stores/spring-ai-pgvector-store/src/main/java/org/springframework/ai/vectorstore/pgvector/PgVectorStore.java
=> Fix typo in PgDistanceType enum class

mcp/common/pom.xml, pom.xml, spring-ai-docs/src/main/asciidoc/mcp.md
- Move MCP BOM dependency management configuration into spring-ai parent
Resolves #2180
=> Update MCP dependency management

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/perplexity-chat.adoc
fix the unavailable sample code
=> fix sample code in perplexity-chat.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc
This documents the usage of the AzureOpenAIClientBuilderCustomizer that was introduced here:
https://github.com/spring-projects/spring-ai/pull/2092
https://github.com/spring-projects/spring-ai/commit/bdd0aa118a78aa47c85bce43a6574eb65979eb0c
ping @sobychacko
=> document AzureOpenAIClientBuilderCustomizer

models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/metadata/AzureOpenAiChatModelMetadataTests.java, spring-ai-core/src/test/java/org/springframework/ai/vectorstore/filter/converter/SimpleVectorStoreFilterExpressionConverterTests.java
replace wildcard imports with explicit class imports
=> refactor: replace wildcard imports with explicit class imports

auto-configurations/spring-ai-mcp-client/pom.xml, auto-configurations/spring-ai-mcp-server/pom.xml
- Adding Spring Boot configuration processor for the tools autocompletion support
Resolves #2273
=> Add boot configuration processor to MCP Autoconfiguration POMs

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/bedrock-converse.adoc
fix sample code in bedrock-converse.adoc
=> fix sample code in bedrock-converse.adoc

auto-configurations/spring-ai-mcp-server/src/main/java/org/springframework/ai/autoconfigure/mcp/server/McpServerAutoConfiguration.java, auto-configurations/spring-ai-mcp-server/src/main/java/org/springframework/ai/autoconfigure/mcp/server/McpServerProperties.java, auto-configurations/spring-ai-mcp-server/src/main/java/org/springframework/ai/autoconfigure/mcp/server/McpWebFluxServerAutoConfiguration.java, auto-configurations/spring-ai-mcp-server/src/main/java/org/springframework/ai/autoconfigure/mcp/server/McpWebMvcServerAutoConfiguration.java, auto-configurations/spring-ai-mcp-server/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, auto-configurations/spring-ai-mcp-server/src/test/java/org/springframework/ai/autoconfigure/mcp/server/McpServerAutoConfigurationIT.java, spring-ai-docs/src/main/asciidoc/mcp.md
Fix identified typo in issue #2285
=> rename files from Mpc to Mcp for consistency

models/spring-ai-ollama/src/main/java/org/springframework/ai/ollama/api/OllamaModel.java
Add new Ollama models: LLAMA3_2_3B
=> Add new Ollama models: LLAMA3_2_3B

auto-configurations/spring-ai-mcp-server/src/main/java/org/springframework/ai/autoconfigure/mcp/server/McpServerAutoConfiguration.java
- Remove unused imports
- Fix typos in variable names (e.g., toolResgistrations -> toolRegistrations)
=> fix(mcp-server): improve code quality and readability

models/spring-ai-vertex-ai-gemini/src/main/java/org/springframework/ai/vertexai/gemini/VertexAiGeminiChatOptions.java
=> chore: add missing toolCallbacks(vargs) to vertex chat options

auto-configurations/spring-ai-mcp-client/src/main/java/org/springframework/ai/autoconfigure/mcp/client/SseHttpClientTransportAutoConfiguration.java, document-readers/tika-reader/src/test/java/org/springframework/ai/reader/tika/TikaDocumentReaderTests.java, mcp/common/src/main/java/org/springframework/ai/mcp/AsyncMcpToolCallback.java, spring-ai-core/src/main/java/org/springframework/ai/chat/client/advisor/QuestionAnswerAdvisor.java, spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/couchbase/CouchbaseSearchVectorStoreAutoConfiguration.java, spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/postgresml/PostgresMlAutoConfigurationIT.java, vector-stores/spring-ai-milvus-store/src/test/java/org/springframework/ai/vectorstore/milvus/MilvusVectorStoreTest.java
=> chore: remove unused imports

spring-ai-bom/pom.xml
=> Add missing vector store autoconfig coorindates to spring-ai-bom

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/tools.adoc
=> Update tools.adoc , change colon to semicolon

auto-configurations/models/chat/memory/spring-ai-autoconfigure-model-chat-memory-neo4j/pom.xml, document-readers/jsoup-reader/pom.xml, pom.xml, spring-ai-client-chat/pom.xml, spring-ai-model/pom.xml, vector-stores/spring-ai-azure-cosmos-db-store/pom.xml, vector-stores/spring-ai-gemfire-store/pom.xml, vector-stores/spring-ai-mongodb-atlas-store/pom.xml, vector-stores/spring-ai-neo4j-store/pom.xml
- Extract common dependency versions to properties in root pom
- Added jsoup.version property
- Added mockk-jvm.version property
- Added neo4j-cypher-dsl-bom.version property
- Update dependency versions:
- djl from 0.30.0 to 0.32.0
- oci-sdk from 3.51.0 to 3.63.1
- azure-identity from 1.14.0 to 1.15.4
- Remove hardcoded versions for consistency
- Minor polishing
=> Update dependencies and cleanup misc version management

spring-ai-model/src/main/java/org/springframework/ai/model/function/FunctionCallback.java
=> chore: Fix typo in toolContext.

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/advisors.adoc
Was going through the notes and noticed this.
=> Docs don't show these as bullets because they are in a note block.

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/retrieval-augmented-generation.adoc
=> Fix typo in retrieval-augmented-generation.adoc

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
=> Remove broken example applications from list

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
=> Update deprecated Media constructor usage in docs

mcp/common/src/test/java/org/springframework/ai/mcp/ToolUtilsTests.java
- Tests empty client list handling returns empty result
- Tests single client with multiple tools correctly generates tool callbacks with prefixed names
- Tests multiple clients properly combine their tool callbacks
- Tests duplicate tool names across clients throw appropriate exceptions
=> Add tests for McpToolUtils.getToolCallbacksFromSyncClients method

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/azure-openai-chat.adoc
=> docs: fix azure-openai-chat gradle dependencies

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat/anthropic-chat.adoc
I forgot to change some documentation along with the improvement https://github.com/spring-projects/spring-ai/pull/2869
=> added custom path in doc

models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiApi.java
=> fix: OpenAiApi comment.

spring-ai-docs/src/main/antora/modules/ROOT/nav.adoc, spring-ai-docs/src/main/antora/modules/ROOT/pages/api/moderation/mistral-ai-moderation.adoc
This PR adds the Mistral AI moderation doc to the Moderation section
=> Documentation of the Mistral Moderation model

spring-ai-docs/src/main/antora/modules/ROOT/pages/upgrade-notes.adoc
=> [Doc] fix doc error

pom.xml, spring-ai-spring-boot-starters/spring-ai-starter-model-chat-memory/pom.xml
- Add Spring Boot starter for Chat memory with in-memory chat memory repository
=> Add Chat memory (in-memory chat memory repository) starter

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/mcp/mcp-server-boot-starter-docs.adoc
=> docs: Document the MCP ToolContext support

spring-ai-vector-store/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Add metadata support for vector store types
=> Add metadata support for vector store types

auto-configurations/models/spring-ai-autoconfigure-model-azure-openai/src/test/java/org/springframework/ai/model/azure/openai/autoconfigure/tool/FunctionCallWithFunctionBeanIT.java, auto-configurations/models/spring-ai-autoconfigure-model-azure-openai/src/test/java/org/springframework/ai/model/azure/openai/autoconfigure/tool/FunctionCallWithFunctionWrapperIT.java, auto-configurations/models/spring-ai-autoconfigure-model-azure-openai/src/test/java/org/springframework/ai/model/azure/openai/autoconfigure/tool/FunctionCallWithPromptFunctionIT.java, models/spring-ai-mistral-ai/src/main/java/org/springframework/ai/mistralai/api/MistralAiModerationApi.java, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiImageApi.java, models/spring-ai-openai/src/main/java/org/springframework/ai/openai/api/OpenAiModerationApi.java, models/spring-ai-zhipuai/src/main/java/org/springframework/ai/zhipuai/api/ZhiPuAiImageApi.java
=> correct @formatter:onn to @formatter:on

models/spring-ai-openai/pom.xml
=> chore: Remove useless proerties tags

spring-ai-model/src/main/java/org/springframework/ai/tool/method/MethodToolCallbackProvider.java, spring-ai-model/src/test/java/org/springframework/ai/tool/method/MethodToolCallbackProviderTest.java
=> fix method tool call throws same method name

spring-ai-docs/src/main/antora/modules/ROOT/pages/api/chat-memory.adoc
Small documentation update: change from PostgresChatMemoryDialect to PostgresChatMemoryRepositoryDialect.
=> doc: update chat-memory.adoc

pom.xml
add <maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
* Add a Signed-off-by line to each commit (`git commit -s`) per the [DCO](https://spring.io/blog/2025/01/06/hello-dco-goodbye-cla-simplifying-contributions-to-spring#how-to-use-developer-certificate-of-origin)
[1]: https://github.com/spring-projects/spring-ai/blob/main/CONTRIBUTING.adoc
=> build: define version of plugin `maven-gpg-plugin`

models/spring-ai-bedrock/src/test/java/org/springframework/ai/bedrock/cohere/BedrockCohereEmbeddingModelIT.java
Replace the expired annotation @SpyBean with annotation @MockitoSpyBean
=> fix: Replace the expired annotation

pom.xml
- update mcp java sdk to 0.13.0
- update mpc-annotations to 0.4.0
=> Update MCP dependencies
